import { useCallback, useEffect, useRef, useState } from 'react'
import Brand from '../Brand'
import { localBackendUrl } from '../workspace/transport'
import { outlinePages, parseSlideBrief, type SlideBrief, type SlideJob, type SlideDesign } from '../../shared/slides'
import './slides.css'
const states={queued:'รอเริ่ม',running:'กำลังสร้างและตรวจไฟล์',cancelling:'กำลังยกเลิก',cancelled:'ยกเลิกแล้ว',error:'สร้างไม่สำเร็จ',ready:'ไฟล์พร้อมแล้ว'}
const errors: Record<string,string>={invalid:'ตรวจหัวข้อและโครงเรื่อง: 2–8 หน้า ชื่อหน้าไม่เกิน 65 ตัวอักษร และ 1–3 ประโยคต่อหน้า ประโยคละไม่เกิน 115 ตัวอักษร',busy:'มีงานสไลด์กำลังทำอยู่ กรุณารอหรือยกเลิกงานเดิม',unavailable:'ยังไม่ได้ตั้งค่าเครื่องมือสร้างไฟล์ใน backend เครื่องนี้',capacity:'ครบ 16 งานในรอบบริการนี้แล้ว เก็บไฟล์เดิมไว้และเปิดบริการรอบใหม่', 'memory-low':'RAM ว่างน้อยกว่า 256 MB จึงหยุดก่อนเรนเดอร์ ไฟล์เดิมและโครงเรื่องยังอยู่', 'powerpoint-busy':'มี PowerPoint เปิดอยู่ จึงหยุดเรนเดอร์เพื่อรักษางานของคุณ',timeout:'ครบเวลาสูงสุด 90 วินาทีแล้ว งานหยุดและไม่ใช้ผลที่มาช้า','render-failed':'สร้างหรือตรวจภาพไม่ผ่าน โปรดลองใหม่หลังตรวจความพร้อมของเครื่อง', 'not-found':'ไม่พบงานนี้ใน session ที่เชื่อมต่อ','stop-unverified':'ส่งคำขอหยุดแล้ว แต่ยังตรวจยืนยันว่าตัวเรนเดอร์จบไม่ได้ ระบบพักงานใหม่ กรุณาตรวจ PowerPoint แล้วเปิด backend รอบใหม่ ไม่ใช้ผลที่มาช้า'}
export default function SlidesPage(){
 const base=localBackendUrl(location.hostname,import.meta.env.VITE_BACKEND_URL)
 const [connected,setConnected]=useState(false),[title,setTitle]=useState(''),[brief,setBrief]=useState(''),[outline,setOutline]=useState('')
 const [design,setDesign]=useState<SlideDesign>('jarvis')
 const briefs=useRef(new Map<string,SlideBrief>())
 const [review,setReview]=useState<SlideBrief|null>(null),[confirmed,setConfirmed]=useState(false),[parent,setParent]=useState<string|undefined>(),[job,setJob]=useState<SlideJob|null>(null),[history,setHistory]=useState<SlideJob[]>([]),[message,setMessage]=useState(''),[waiting,setWaiting]=useState(false)
 const current=useRef<SlideJob|null>(null),controller=useRef<AbortController|null>(null),alive=useRef(true)
 const busy=waiting || !!job && ['queued','running','cancelling'].includes(job.state)
 const request=useCallback(async(endpoint:string,body?:unknown,signal?:AbortSignal)=>{const response=await fetch(base+endpoint,{method:body===undefined?'GET':'POST',credentials:'include',headers:body===undefined?{}:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:signal?AbortSignal.any([signal,AbortSignal.timeout(10000)]):AbortSignal.timeout(10000)});const value=await response.json();if(!response.ok)throw Error(errors[value.code]??errors['render-failed']);return value},[base])
 function receive(value:SlideJob){current.current=value;setJob(value);setHistory(old=>[value,...old.filter(item=>item.id!==value.id)]);if(value.error)setMessage(errors[value.error]??errors['render-failed'])}
 useEffect(()=>{alive.current=true;const stop=()=>{controller.current?.abort();const value=current.current;if(base && value && ['queued','running'].includes(value.state))void fetch(base+`/slides/jobs/${value.id}/cancel`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:'{}',keepalive:true}).catch(()=>{})};const leaving=()=>{if(location.hash!=='#/slides'){alive.current=false;stop()}};addEventListener('hashchange',leaving);addEventListener('beforeunload',stop);return()=>{alive.current=false;stop();removeEventListener('hashchange',leaving);removeEventListener('beforeunload',stop)}},[base])
 useEffect(()=>{if(!base||!job||!['queued','running','cancelling'].includes(job.state))return;const id=job.id,abort=new AbortController();const timer=setTimeout(()=>{void request(`/slides/jobs/${id}`,undefined,abort.signal).then(value=>{if(alive.current && current.current?.id===id)receive(value)}).catch(()=>{if(!abort.signal.aborted)setMessage('ติดต่อ backend ไม่ได้ งานอาจยังทำอยู่ ใช้ปุ่มตรวจสถานะหรือลองหยุดอีกครั้ง')})},1000);return()=>{clearTimeout(timer);abort.abort()}},[base,job,request])
 function changed(){setReview(null);setConfirmed(false);setMessage('')}
 function check(){try{setReview(parseSlideBrief({title,brief,design,pages:outlinePages(outline),...(parent?{parentId:parent}:{})}));setMessage('ตรวจโครงเรื่องแล้ว กรุณาตรวจเนื้อหาทุกหน้าและยืนยันก่อนสร้างไฟล์')}catch{setMessage(errors.invalid)}}
 async function connect(){if(!base)return;setWaiting(true);setMessage('');try{const status=await request('/slides/status');if(!status.configured)throw Error(errors.unavailable);const response=await fetch(base+'/session',{method:'POST',credentials:'include',signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error('เชื่อมต่อ session ไม่สำเร็จ');if(alive.current){setConnected(true);setMessage('เครื่องมือพร้อม สร้างจากโครงเรื่องที่คุณตรวจ หนึ่งงานต่อครั้ง')}}catch(error){if(alive.current)setMessage(error instanceof Error?error.message:'เชื่อมต่อไม่ได้')}finally{if(alive.current)setWaiting(false)}}
 async function create(){if(!review||!confirmed||!connected||busy)return;setWaiting(true);setMessage('');const abort=new AbortController();controller.current=abort;try{const value=await request('/slides/jobs',review,abort.signal);if(alive.current){briefs.current.set(value.id,review);receive(value)}else void request(`/slides/jobs/${value.id}/cancel`,{}).catch(()=>{})}catch(error){if(alive.current&&!abort.signal.aborted)setMessage(error instanceof Error?error.message:'สร้างไม่สำเร็จ')}finally{if(alive.current)setWaiting(false);if(controller.current===abort)controller.current=null}}
 async function cancel(){controller.current?.abort();if(!current.current)return;try{receive(await request(`/slides/jobs/${current.current.id}/cancel`,{}))}catch(error){setMessage(error instanceof Error?error.message:'หยุดไม่สำเร็จ')}}
 const file=(name:string)=>`${base}/slides/jobs/${job?.id}/files/${name}`
 return <div className="cic-slides"><header><Brand href="#/app"/><a href="#/app">กลับแชต</a></header><main><h1>สไลด์ในเครื่อง</h1><p className="intro">เลือกแบบ A มืออาชีพ หรือแบบ B จาวิส สร้าง PPTX ที่แก้ไขได้จากโครงเรื่องที่คุณตรวจ พร้อมภาพจาก PowerPoint และ PDF</p><p className="limit">ตัวสร้างไฟล์ยังไม่วางเนื้อหาไทยให้เอง ไม่ใช้ AI ภายนอก และไม่ได้อ่านหรือควบคุมหน้าจอ</p>
 {!base?<p role="status">เว็บสาธารณะเป็น demo เปิดเว็บและ backend ในเครื่องที่ 127.0.0.1 เพื่อสร้างไฟล์ ไม่มีการเรียก backend จากหน้านี้</p>:<button disabled={waiting||connected} onClick={()=>void connect()}>{connected?'เชื่อมต่อเครื่องมือแล้ว':'ตรวจเครื่องมือในเครื่อง'}</button>}
 <section aria-label="โจทย์และโครงเรื่อง"><h2>โจทย์และโครงเรื่อง</h2><fieldset disabled={busy} className="design-picker"><legend>รูปแบบสไลด์</legend><label><input type="radio" name="slide-design" value="professional" checked={design==='professional'} onChange={()=>{changed();setDesign('professional')}}/>แบบ A มืออาชีพ <span>พื้นสว่าง เนื้อหาเรียบชัด</span></label><label><input type="radio" name="slide-design" value="jarvis" checked={design==='jarvis'} onChange={()=>{changed();setDesign('jarvis')}}/>แบบ B จาวิส <span>พื้นกรมเข้ม เน้นสีฟ้าไซแอน</span></label></fieldset><label>ชื่อผลงาน<input maxLength={70} value={title} disabled={busy} onChange={e=>{changed();setTitle(e.target.value)}}/></label><label>โจทย์และข้อเท็จจริง<textarea maxLength={1500} rows={3} value={brief} disabled={busy} onChange={e=>{changed();setBrief(e.target.value)}}/></label><label>โครงเรื่อง 2–8 หน้า<textarea rows={10} maxLength={5000} value={outline} disabled={busy} placeholder={'ชื่อหน้าแรก\nประโยคสำหรับหน้าแรก\n\nชื่อหน้าที่สอง\nประโยคสำหรับหน้าที่สอง'} onChange={e=>{changed();setOutline(e.target.value)}}/></label><p>แยกหน้าด้วยบรรทัดว่าง บรรทัดแรกเป็นชื่อหน้า ตามด้วย 1–3 ประโยค ประโยคละไม่เกิน 115 ตัวอักษร</p><button onClick={check} disabled={busy}>ตรวจโครงเรื่อง</button>{parent&&<p>ฉบับแก้ไขจะสร้างงานใหม่และเก็บไฟล์ต้นฉบับไว้</p>}</section>
 {review&&<section aria-label="โครงเรื่องที่ตรวจ"><h2>ตรวจเนื้อหาก่อนสร้าง</h2><p>รูปแบบ: {review.design==='jarvis'?'B จาวิส':'A มืออาชีพ'}</p>{review.pages.map((page,i)=><article key={i}><h3>{i+1}. {page.title}</h3>{page.body.map((line,j)=><p key={j}>{line}</p>)}</article>)}<label className="confirmation"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>ฉันตรวจข้อมูลและลำดับหน้าแล้ว</label><button onClick={()=>void create()} disabled={!base||!connected||!confirmed||busy}>สร้างไฟล์สไลด์</button></section>}
 <p role="status" aria-live="polite">{job?states[job.state]:''}{message?' · '+message:''}</p>{job&&['queued','running','cancelling'].includes(job.state)&&<><button onClick={()=>void cancel()} disabled={job.state==='cancelling'}>ยกเลิกงานสไลด์</button><button onClick={()=>void request(`/slides/jobs/${job.id}`).then(receive).catch(()=>setMessage('ตรวจสถานะไม่สำเร็จ'))}>ตรวจสถานะ</button></>}
 {job?.state==='ready'&&<section aria-label="ผลลัพธ์สไลด์"><h2>{job.title}</h2><p>รูปแบบ: {job.design==='jarvis'?'B จาวิส':'A มืออาชีพ'}</p><div className="downloads"><a href={file('deck.pptx')} download>ดาวน์โหลด PPTX</a><a href={file('deck.pdf')} download>ดาวน์โหลด PDF</a><button disabled={busy} onClick={()=>{const saved=briefs.current.get(job.id);if(saved){setTitle(saved.title);setBrief(saved.brief);setOutline(saved.pages.map(page=>[page.title,...page.body].join('\n')).join('\n\n'));setDesign(saved.design??'professional')}else setDesign(job.design??'professional');setParent(job.id);setConfirmed(false);setReview(null);setMessage('แก้โครงเรื่องด้านบน แล้วตรวจและสร้างฉบับใหม่')}}>แก้เด็คนี้</button></div><p>เครื่องมือเปิดไฟล์ใน PowerPoint และตรวจความสูงข้อความแล้ว คุณควรดูภาพทุกหน้าก่อนใช้งานจริง</p><div className="previews">{Array.from({length:job.pageCount},(_,i)=><figure key={i}><img src={file(`slide-${String(i+1).padStart(2,'0')}.png`)} alt={`สไลด์หน้า ${i+1}`} loading="lazy"/><figcaption>หน้า {i+1}</figcaption></figure>)}</div></section>}
 {history.length>1&&<section aria-label="งานก่อนหน้า"><h2>งานก่อนหน้า</h2>{history.filter(item=>item.id!==job?.id).map(item=><button key={item.id} disabled={busy} onClick={()=>{current.current=item;setJob(item);setMessage('')}}>{item.title} · {states[item.state]}</button>)}</section>}
 <p className="limit">ไฟล์ผู้ใช้แยกจากตัวอย่าง เก็บในเครื่องโดยไม่เขียนทับ ไม่ลบอัตโนมัติ รายการในหน้านี้หายเมื่อรีเฟรชหรือปิดบริการ เก็บไฟล์ที่ต้องการด้วยปุ่มดาวน์โหลดก่อน</p></main></div>
}
