import {test,expect} from '@playwright/test'
import {once} from 'node:events'
import {randomUUID} from 'node:crypto'
import {createLabCore} from '../backend/lab/core'
import {createChatServer} from '../backend/server'
import {LAB_ACTIONS,type LabObservation} from '../shared/lab'
test('Lab reviewed flow and responsive layout (fixture native adapter, real server)',async({page})=>{
 let live=true;const o:LabObservation={instanceId:randomUUID(),observationId:randomUUID(),monotonicMs:performance.now(),geometry:'fixture',foreground:true,clicks:0,text:'',slider:0,top:0,dpi:96,source:'owned-window-structure',availableActions:[...LAB_ACTIONS],targets:LAB_ACTIONS.map((id,i)=>({id,name:id,x:20+i*30,y:200,width:100,height:45}))};const lab=createLabCore({externalBusy:()=>false,ownerAlive:()=>true,freeMiB:()=>1024,start:async()=>({alive:()=>live,close:async()=>{live=false},observe:async()=>structuredClone(o),execute:async()=>{const before=structuredClone(o);o.clicks++;return{before,after:structuredClone(o)}}})}),server=createChatServer({lab,origins:['http://127.0.0.1:4173'],requestsPerMinute:100});server.listen(0,'127.0.0.1');await once(server,'listening');const base='http://127.0.0.1:'+(server.address() as {port:number}).port;
 try{await page.route('http://127.0.0.1:8787/**',async route=>{const r=await route.fetch({url:route.request().url().replace('http://127.0.0.1:8787',base)});await route.fulfill({response:r})});await page.goto('./#/lab');await page.getByRole('button',{name:'ตรวจบริการ Lab',exact:true}).click();await expect(page.getByRole('button',{name:'เปิดหน้าต่าง CIC Lab',exact:true})).toBeDisabled();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'เปิดหน้าต่าง CIC Lab',exact:true}).click();await expect(page.getByRole('status')).toContainText('เปิด CIC Lab แล้ว');
 const second=await page.context().newPage();await second.route('http://127.0.0.1:8787/**',async route=>{const r=await route.fetch({url:route.request().url().replace('http://127.0.0.1:8787',base)});await route.fulfill({response:r})});await second.goto('http://127.0.0.1:4173/CIC-bot/#/lab');await second.goto('about:blank');await second.unrouteAll({behavior:'wait'});await second.close();expect(live).toBe(true);
 await page.getByRole('button',{name:'วางแผน Lab หนึ่งงาน',exact:true}).click();await expect(page.getByRole('heading',{name:'รอคุณตรวจแผน',exact:true})).toBeVisible();expect(o.clicks).toBe(0);await page.getByRole('button',{name:'อนุญาตแผนนี้หนึ่งครั้ง',exact:true}).click();await expect(page.getByRole('heading',{name:'ทำแล้วและตรวจผลตรง',exact:true})).toBeVisible();await expect(page.getByRole('article',{name:'งาน Lab'})).toContainText('ปุ่มได้รับคลิก: 1');for(const[width,height]of[[1440,900],[390,844],[360,480]]){await page.setViewportSize({width,height});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'.tools/lab-fixture-'+width+'.png',fullPage:true})}await page.getByRole('button',{name:'หยุดและปิด Lab ของฉัน',exact:true}).click();await expect(page.getByRole('status')).toContainText('โปรเซส Lab ของคุณออกแล้ว');expect(live).toBe(false)}finally{await page.unrouteAll({behavior:'wait'});server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await lab.close()}
})
test('public Lab is demo: no localhost calls or control grants',async({page})=>{const calls:string[]=[];page.on('request',r=>{if(/:8787|:11434/.test(r.url()))calls.push(r.url())});await page.route('http://lab-demo.test/**',async route=>{const r=await route.fetch({url:route.request().url().replace('http://lab-demo.test','http://127.0.0.1:4173')});await route.fulfill({response:r})});await page.goto('http://lab-demo.test/CIC-bot/#/lab');await expect(page.getByRole('button',{name:'ตรวจบริการ Lab',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'เปิดหน้าต่าง CIC Lab',exact:true})).toBeDisabled();await expect(page.getByRole('checkbox')).toBeDisabled();expect(calls).toEqual([])})
