import {test,expect} from '@playwright/test'
import {randomUUID} from 'node:crypto'
import {once} from 'node:events'
import {createLabCore} from '../backend/lab/core'
import {createChatServer} from '../backend/server'
import {parseLabPlan,parseLabJob,LAB_ACTIONS,type LabObservation} from '../shared/lab'
import type {LabNative} from '../backend/lab/native'
import {createCore} from '../backend/core/core'
import {createScheduler} from '../backend/core/scheduler'
function fixture(){let live=true,calls=0;const o:LabObservation={instanceId:randomUUID(),observationId:randomUUID(),monotonicMs:performance.now(),geometry:'fixture-geometry',foreground:true,clicks:0,text:'',slider:0,top:0,dpi:96,source:'owned-window-structure',availableActions:[...LAB_ACTIONS],targets:LAB_ACTIONS.map((id,i)=>({id,name:id,x:i*41-200,y:55,width:100,height:40}))};const native:LabNative={alive:()=>live,close:async()=>{live=false},observe:async()=>structuredClone(o),execute:async(action,text,_g,signal)=>{signal.throwIfAborted();calls++;const before=structuredClone(o);if(action==='click')o.clicks++;else if(action==='type')o.text=text;else if(action==='slider')o.slider=75;else o.top+=5;return {before,after:structuredClone(o)}}};return{native,get calls(){return calls},move:()=>{o.geometry='moved'},corrupt:()=>{o.foreground=false}}}
const open=(core:ReturnType<typeof createLabCore>,owner='a')=>core.open(owner,{version:1,operationId:randomUUID(),acknowledged:true})
const input=(action:string='click',text='')=>({version:1,operationId:randomUUID(),action,text})
test('closed lab plans reject arbitrary native/shell targets, references and control text',()=>{for(const v of [{...input(),hwnd:1},{...input(),action:'sendinput'},{...input(),reference:'approve'},{...input('type','x\nshutdown')},{...input('click','x')},{...input('type','')},{...input('type','a'.repeat(41))}])expect(()=>parseLabPlan(v)).toThrow();expect(parseLabPlan(input('type','ทดสอบใหม่ 497'))).toBeTruthy()})
test('UI protocol rejects failed jobs carrying success evidence or forged source/unknown authority',()=>{const job={version:1,taskId:randomUUID(),operationId:randomUUID(),action:'click',text:'',state:'failed',events:[]};const result={source:'native-uia-lab',verified:true,text:'count1'};expect(()=>parseLabJob({...job,result})).toThrow();expect(()=>parseLabJob({...job,grant:'forged'})).toThrow();expect(()=>parseLabJob({...job,state:'succeeded',result:{...result,source:'model'}})).toThrow();expect(parseLabJob(job).state).toBe('failed')})
test('delayed observation cancellation and stop during startup cannot resurrect a helper or plan (fixture)',async()=>{const f=fixture();let releaseStart:(n:LabNative)=>void=()=>{};const lab=createLabCore({externalBusy:()=>false,ownerAlive:()=>true,freeMiB:()=>1024,start:()=>new Promise(r=>{releaseStart=r})});try{const opening=open(lab).catch(e=>e),stopping=lab.stop('a');expect(lab.isBusy()).toBe(true);releaseStart(f.native);expect(await opening).toBeInstanceOf(Error);expect(await stopping).toEqual({settled:true});expect(f.native.alive()).toBe(false)}finally{await lab.close()}
 const g=fixture(),next=createLabCore({externalBusy:()=>false,ownerAlive:()=>true,freeMiB:()=>1024,start:async()=>g.native});try{await open(next);let release:((o:LabObservation)=>void)=()=>{};const snapshot=await g.native.observe();g.native.observe=()=>new Promise(r=>{release=r});const p=input(),planning=next.plan('a',p).catch(e=>e);await next.cancelOperation('a',p.operationId);release(snapshot);expect(await planning).toBeInstanceOf(Error);expect(g.calls).toBe(0)}finally{await next.close()}})
test('shared production-style queue serializes calculator and Lab with separate RAM reserves (fixture)',async()=>{const f=fixture();let free=1024;const scheduler=createScheduler({freeMiB:()=>free,externalBusy:()=>false}),core=createCore({scheduler}),lab=createLabCore({scheduler,externalBusy:()=>scheduler.busy(),ownerAlive:()=>true,freeMiB:()=>free,start:async()=>f.native});try{await open(lab);free=550;const native=await lab.plan('a',input());lab.approve('a',native.taskId);await expect.poll(()=>lab.get('a',native.taskId).reason).toBe('memory');expect(f.calls).toBe(0);const math=core.plan('b',{version:1,operationId:randomUUID(),instruction:'/calc 17+23'});core.approve('b',math.taskId);expect(scheduler.snapshot().queued).toBe(2);free=1024;await expect.poll(()=>lab.get('a',native.taskId).state).toBe('succeeded');await expect.poll(()=>core.get('b',math.taskId).state).toBe('succeeded');expect(core.get('b',math.taskId).result?.text).toBe('17+23 = 40')}finally{core.close();await lab.close()}})
test('four typed effects require review, verify changed state, one use and owner binding (fixture adapter)',async()=>{const f=fixture(),core=createLabCore({externalBusy:()=>false,ownerAlive:()=>true,freeMiB:()=>1024,start:async()=>f.native});try{await open(core);for(const action of LAB_ACTIONS){const j=await core.plan('a',input(action,action==='type'?'ข้อความใหม่ 829':''));expect(f.calls).toBe(LAB_ACTIONS.indexOf(action));expect(()=>core.approve('b',j.taskId)).toThrow();core.approve('a',j.taskId);await expect.poll(()=>core.get('a',j.taskId).state).toBe('succeeded');expect(core.get('a',j.taskId).result?.source).toBe('native-uia-lab');expect(()=>core.approve('a',j.taskId)).toThrow()}expect(f.calls).toBe(4)}finally{await core.close()}})
test('geometry change and verifier failure never certify success; invalid scope cannot open (fixture)',async()=>{const f=fixture(),core=createLabCore({externalBusy:()=>false,ownerAlive:()=>true,freeMiB:()=>1024,start:async()=>f.native});try{await expect(core.open('a',{version:1,operationId:randomUUID(),acknowledged:false})).rejects.toThrow();await open(core);let j=await core.plan('a',input());f.move();core.approve('a',j.taskId);await expect.poll(()=>core.get('a',j.taskId).state).toBe('failed');expect(f.calls).toBe(0);j=await core.plan('a',input());f.corrupt();core.approve('a',j.taskId);await expect.poll(()=>core.get('a',j.taskId).state).toBe('failed');expect(core.get('a',j.taskId).result).toBeUndefined()}finally{await core.close()}})
test('cancel-before-create/open tombstone and cancellation during async observation prevent late work (fixture)',async()=>{const f=fixture(),core=createLabCore({externalBusy:()=>false,ownerAlive:()=>true,freeMiB:()=>1024,start:async()=>f.native});try{const op=randomUUID();await core.cancelOperation('a',op);await expect(core.open('a',{version:1,operationId:op,acknowledged:true})).rejects.toThrow('replay');await open(core);const p=input();await core.cancelOperation('a',p.operationId);await expect(core.plan('a',p)).rejects.toThrow('replay');expect(f.calls).toBe(0)}finally{await core.close()}})
test('low RAM/deadline and stop hold actual executor until owned exit (fixture)',async()=>{const f=fixture();let free=1024,resolveClose:(()=>void)|undefined;f.native.close=()=>new Promise<void>(r=>{resolveClose=r});f.native.execute=async(_a,_t,_g,signal)=>new Promise((_r,reject)=>signal.addEventListener('abort',()=>reject(Error('cancelled')),{once:true}));const core=createLabCore({externalBusy:()=>false,ownerAlive:()=>true,freeMiB:()=>free,start:async()=>f.native,deadlineMs:2000});try{free=400;await expect(open(core)).rejects.toThrow('memory');free=1024;await open(core);const j=await core.plan('a',input());core.approve('a',j.taskId);await expect.poll(()=>core.get('a',j.taskId).state).toBe('running');const stop=core.stop('a');await expect.poll(()=>core.get('a',j.taskId).state).toBe('stop-unverified');expect(core.isBusy()).toBe(true);resolveClose!();expect(await stop).toEqual({settled:true});expect(core.get('a',j.taskId).state).toBe('cancelled')}finally{f.native.close=async()=>{};await core.close()}})
test('authenticated Lab HTTP rejects foreign owner, origin and raw coordinates (fixture)',async()=>{const f=fixture(),lab=createLabCore({externalBusy:()=>false,ownerAlive:()=>true,freeMiB:()=>1024,start:async()=>f.native}),server=createChatServer({lab,requestsPerMinute:100});server.listen(0,'127.0.0.1');await once(server,'listening');const base='http://127.0.0.1:'+(server.address() as {port:number}).port,origin='http://127.0.0.1:5173';const session=async()=>{const r=await fetch(base+'/session',{method:'POST',headers:{Origin:origin}});return r.headers.get('set-cookie')!.split(';')[0]};const a=await session(),b=await session();const post=(path:string,v:unknown,cookie=a,who=origin)=>fetch(base+path,{method:'POST',headers:{Origin:who,Cookie:cookie,'Content-Type':'application/json'},body:JSON.stringify(v)});try{expect((await post('/lab/open',{version:1,operationId:randomUUID(),acknowledged:true},a,'http://evil.test')).status).toBe(403);expect((await post('/lab/open',{version:1,operationId:randomUUID(),acknowledged:true})).status).toBe(201);expect((await post('/lab/plans',{...input(),x:12,y:33})).status).toBe(400);const j=await(await post('/lab/plans',input())).json();expect((await post('/lab/jobs/'+j.taskId+'/approve',{},b)).status).toBe(404);expect((await fetch(base+'/lab/jobs/'+j.taskId,{headers:{Cookie:b}})).status).toBe(404);expect((await post('/lab/stop',{})).status).toBe(200)}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await lab.close()}})
