import { test, expect, type Page } from '@playwright/test'

const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aF9sAAAAASUVORK5CYII=', 'base64')
const input = (page: Page) => page.getByRole('textbox', { name: 'ข้อความถึง CIC' })
async function send(page: Page, text: string) { await input(page).fill(text); await page.getByRole('button', { name: 'ส่งข้อความ', exact: true }).click() }
async function connect(page: Page) {
  await page.getByRole('button', { name: 'เลือกหน้าจอจำลอง', exact: true }).click()
  await page.getByRole('dialog', { name: 'ลองเลือกหน้าจอ', exact: true }).getByRole('button', { name: /หน้าต่างโปรแกรม/ }).click()
  await expect(page.getByRole('dialog', { name: 'ลองเลือกหน้าจอ', exact: true })).not.toBeVisible()
}

test('save action is accurate; compact preserves pending approval, source, draft and image', async ({ page }) => {
  await page.goto('./#/app'); await connect(page)
  await page.getByRole('button', { name: 'ช่วยทำ', exact: true }).click()
  await send(page, 'ช่วยคลิกปุ่มบันทึกในหน้าต่างนี้')
  await expect(page.getByRole('heading', { name: 'จำลองคลิกปุ่มบันทึก', exact: true })).toBeVisible()
  await expect(page.getByRole('article', { name: 'คำตอบจำลอง CIC' })).toContainText('ชื่อปุ่ม: บันทึก')
  await input(page).fill('ร่างที่ยังไม่ส่ง')
  await page.getByLabel('แนบรูปภาพ', { exact: true }).setInputFiles({ name: 'draft.png', mimeType: 'image/png', buffer: png })
  await expect(page.getByRole('img', { name: 'ภาพแนบ draft.png' })).toBeVisible()
  await page.getByRole('button', { name: 'มุมมองกะทัดรัด', exact: true }).click()
  const main = await page.getByRole('main').boundingBox()
  expect(main!.x).toBeGreaterThan(950)
  expect(main!.x + main!.width).toBeGreaterThan(1435)
  await expect(input(page)).toHaveValue('ร่างที่ยังไม่ส่ง')
  await expect(page.getByRole('img', { name: 'ภาพแนบ draft.png' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'อนุญาตการจำลองนี้' })).toBeVisible()
  await page.getByRole('button', { name: 'เปิดบริบท', exact: true }).click()
  const context = page.getByRole('dialog', { name: 'บริบทหน้าจอ', exact: true })
  await expect(context).toContainText('หน้าต่างตัวอย่าง — VS Code')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'อนุญาตการจำลองนี้' }).click()
  await expect(page.getByText('เสร็จแล้ว · ผลจำลอง', { exact: true })).toBeVisible()
  await expect(page.getByRole('article', { name: 'คำตอบจำลอง CIC' })).toContainText('จำลองคลิกปุ่มบันทึก เสร็จแล้ว')
  await page.screenshot({ path: 'test-results/readiness-compact-save.png' })
  await page.getByRole('button', { name: 'กลับ Workspace' }).click()
  await expect(input(page)).toHaveValue('ร่างที่ยังไม่ส่ง')
  await page.getByRole('button', { name: 'ลบ draft.png' }).click()
  await expect(page.getByRole('article')).toHaveCount(2)
})

test('partial streaming can stop and leave the app without late replies; new work starts normally', async ({ page }) => {
  await page.clock.install()
  await page.goto('./#/app'); await connect(page)
  await page.clock.pauseAt(await page.evaluate(() => Date.now() + 1000))
  await send(page, 'วางแผนงาน')
  await page.clock.runFor(150)
  await expect(page.getByText('กำลังทยอยตอบ…', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'หยุดงาน', exact: true }).click()
  const partial = page.getByRole('article', { name: 'คำตอบจำลอง CIC' })
  const stopped = await partial.textContent()
  await expect(partial).toContainText('หยุดกลางทาง')
  await expect(page.getByText(/หยุดงานแล้ว · ยังเลือก หน้าต่างตัวอย่าง/)).toBeVisible()
  await page.clock.runFor(1000)
  expect(await partial.textContent()).toBe(stopped)
  await send(page, 'วางแผนงานใหม่'); await page.clock.runFor(1000)
  await expect(page.getByRole('button', { name: 'หยุดงาน', exact: true })).toBeDisabled()
  await send(page, 'วิเคราะห์โค้ด'); await page.clock.runFor(150)
  await expect(page.getByText('กำลังทยอยตอบ…', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'กลับหน้าแนะนำ', exact: true }).click()
  await expect(page).toHaveURL(/#top$/)
  await page.clock.runFor(1000)
  await page.getByRole('button', { name: 'เข้าใช้งาน', exact: true }).first().click()
  await expect(page.getByRole('article', { name: 'คำตอบจำลอง CIC' }).last()).toContainText('หยุดกลางทาง')
  await expect(page.getByRole('article', { name: 'คำตอบจำลอง CIC' }).last()).not.toContainText('function greeting')
})

test('attachment removal does not send draft, invalid images and limits recover, refresh clears session', async ({ page }) => {
  await page.goto('./#/app')
  await input(page).fill('   \n  ')
  await expect(page.getByRole('button', { name: 'ส่งข้อความ', exact: true })).toBeDisabled()
  await input(page).fill('ร่างยังไม่ส่ง')
  const upload = page.getByLabel('แนบรูปภาพ', { exact: true })
  await upload.setInputFiles({ name: 'broken.png', mimeType: 'image/png', buffer: Buffer.from('not an image') })
  await expect(page.getByRole('alert')).toContainText('เปิดภาพไม่ได้')
  await upload.setInputFiles({ name: 'good.png', mimeType: 'image/png', buffer: png })
  await expect(page.getByRole('img', { name: 'ภาพแนบ good.png' })).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.getByRole('button', { name: 'ลบ good.png' }).click()
  await expect(input(page)).toHaveValue('ร่างยังไม่ส่ง')
  await expect(page.getByRole('article')).toHaveCount(0)
  for (let i = 0; i < 6; i++) {
    await page.getByRole('button', { name: 'ลิงก์', exact: true }).click()
    const modal = page.getByRole('dialog', { name: 'แนบลิงก์' })
    await modal.getByRole('textbox').fill(`https://example.com/${i}`)
    await modal.getByRole('button', { name: 'เพิ่มลิงก์' }).click()
  }
  await upload.setInputFiles({ name: 'seventh.png', mimeType: 'image/png', buffer: png })
  await expect(page.getByRole('alert')).toContainText('สูงสุด 6')
  await page.getByRole('button', { name: 'ลบ example.com', exact: true }).first().click()
  await upload.setInputFiles({ name: 'last.png', mimeType: 'image/png', buffer: png })
  await expect(page.getByRole('img', { name: 'ภาพแนบ last.png' })).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.getByText('ข้อจำกัดสิ่งแนบ', { exact: true }).click()
  await expect(page.getByText(/สูงสุด 6 รายการต่อข้อความ · ภาพ PNG/)).toBeVisible()
  await page.reload()
  await expect(input(page)).toHaveValue('')
  await expect(page.getByRole('img')).toHaveCount(0)
  await expect(page.getByRole('article')).toHaveCount(0)
})

test('long chat title, small height and nested context dialog preserve controls and focus', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 480 })
  await page.goto('./#/app')
  await send(page, 'วางแผนงานที่มีชื่อยาวมากและรายละเอียดจำนวนมาก'.repeat(3))
  await expect(page.getByRole('button', { name: 'หยุดงาน', exact: true })).toBeDisabled()
  await expect(page.getByRole('group', { name: 'โหมดผู้ช่วย' })).toBeInViewport()
  await expect(page.getByRole('button', { name: 'ส่งข้อความ', exact: true })).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.documentElement.scrollHeight <= innerHeight)).toBe(true)
  await page.getByRole('button', { name: 'เปิดบริบท', exact: true }).click()
  await page.getByRole('dialog', { name: 'บริบทหน้าจอ', exact: true }).getByRole('button', { name: 'ลองเลือกหน้าจอ', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'ลองเลือกหน้าจอ', exact: true }).getByRole('button', { name: 'ปิดลองเลือกหน้าจอ' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'บริบทหน้าจอ', exact: true }).getByRole('button', { name: 'ลองเลือกหน้าจอ', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'เปิดบริบท', exact: true })).toBeFocused()
  await page.screenshot({ path: 'test-results/readiness-short-long-title.png' })
})
