import { test, expect, type Page } from '@playwright/test'

async function send(page: Page, text: string) { await page.getByRole('textbox', { name: 'ข้อความถึง CIC' }).fill(text); await page.getByRole('button', { name: 'ส่งข้อความ', exact: true }).click() }
async function selectSource(page: Page, label = 'หน้าต่างโปรแกรม') {
  await page.getByRole('button', { name: 'ลองเลือกหน้าจอ', exact: true }).click()
  await page.getByRole('dialog', { name: 'ลองเลือกหน้าจอ', exact: true }).getByRole('button', { name: new RegExp(label) }).click()
  await expect(page.getByRole('dialog', { name: 'ลองเลือกหน้าจอ', exact: true })).not.toBeVisible()
}
test('hash routes, direct refresh, history, landing anchors, and app avoids Three.js', async ({ page }) => {
  const loaded: string[] = [], errors: string[] = []
  page.on('request', request => loaded.push(request.url()))
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('./#/app')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('วันนี้อยากให้ CIC')
  expect(loaded.some(url => /\/Scene-.*\.js/.test(url))).toBe(false)
  expect(await page.locator('canvas').count()).toBe(0)
  await page.reload()
  await expect(page.getByRole('textbox', { name: 'ข้อความถึง CIC' })).toBeVisible()
  await page.getByRole('link', { name: 'กลับหน้าแนะนำ', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toContainText('ช่วยคิดไปกับทุกงาน')
  await page.getByRole('navigation', { name: 'เมนูหลัก' }).getByRole('link', { name: 'รู้จัก CIC', exact: true }).click()
  await expect(page).toHaveURL(/#about$/)
  await expect(page.locator('#about')).toBeInViewport()
  await page.getByRole('button', { name: 'เข้าใช้งาน', exact: true }).first().click()
  await expect(page).toHaveURL(/#\/app$/)
  await page.goBack(); await expect(page.locator('#about')).toBeInViewport()
  await page.goForward(); await expect(page.getByRole('textbox', { name: 'ข้อความถึง CIC' })).toBeVisible()
  expect(errors).toEqual([])
})
test('suggestions, Enter/Shift+Enter/IME, session history and layout share messages and drafts', async ({ page }) => {
  await page.goto('./#/app')
  const input = page.getByRole('textbox', { name: 'ข้อความถึง CIC' })
  await page.getByRole('button', { name: 'วางแผนงาน', exact: true }).click()
  await expect(input).toHaveValue(/ช่วยวางแผน/)
  expect(await page.getByRole('article').count()).toBe(0)
  await input.press('Shift+Enter'); await expect(input).toHaveValue(/\n$/)
  await input.dispatchEvent('compositionstart')
  await input.press('Enter'); expect(await page.getByRole('article').count()).toBe(0)
  await input.dispatchEvent('compositionend'); await input.press('Enter')
  await expect(page.getByRole('article', { name: 'คำตอบจำลอง CIC' })).toHaveCount(1)
  await input.fill('ร่างที่ยังไม่ส่ง')
  await page.getByRole('button', { name: 'มุมมองกะทัดรัด', exact: true }).click()
  await expect(input).toHaveValue('ร่างที่ยังไม่ส่ง')
  await expect(page.getByRole('article')).toHaveCount(2)
  await page.getByRole('button', { name: 'กลับ Workspace' }).click()
  await page.getByRole('button', { name: 'แชตใหม่', exact: true }).click()
  await expect(page.getByRole('article')).toHaveCount(0)
  await send(page, 'อีกแชตหนึ่ง')
  await expect(page.getByRole('article')).toHaveCount(2)
  await page.getByRole('button', { name: /เปิดแชต ช่วยวางแผน/ }).click()
  await expect(input).toHaveValue('ร่างที่ยังไม่ส่ง')
  await expect(page.getByRole('article')).toHaveCount(2)
  await expect(page.getByRole('article', { name: 'ข้อความของคุณ' })).not.toContainText('อีกแชตหนึ่ง')
})
test('context permissions, approval, reject, stop and stale request invalidation', async ({ page }) => {
  await page.goto('./#/app')
  await selectSource(page)
  await expect(page.getByRole('complementary', { name: 'บริบทหน้าจอ' })).toContainText('พักบริบท')
  await page.getByRole('button', { name: 'ช่วยทำ', exact: true }).click()
  await send(page, 'ช่วยทำรายการงาน')
  await page.getByRole('button', { name: 'ปฏิเสธ', exact: true }).click()
  await expect(page.getByText('ปฏิเสธแล้ว', { exact: true })).toBeVisible()
  await send(page, 'ช่วยทำรายการใหม่')
  await page.getByRole('button', { name: 'อนุญาตการจำลองนี้' }).click()
  await expect(page.getByText('เสร็จแล้ว · ผลจำลอง', { exact: true })).toBeVisible()
  await send(page, 'ช่วยทำรายการอีกครั้ง')
  await expect(page.getByRole('button', { name: 'อนุญาตการจำลองนี้' })).toBeVisible()
  await page.getByRole('button', { name: 'คุย', exact: true }).click()
  await expect(page.getByRole('button', { name: 'อนุญาตการจำลองนี้' })).toHaveCount(0)
  await expect(page.getByText('ยกเลิกแล้ว', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'ช่วยทำ', exact: true }).click()
  await send(page, 'ช่วยทำรายการสุดท้าย')
  await page.getByRole('button', { name: 'อนุญาตการจำลองนี้' }).click()
  await page.getByRole('button', { name: 'หยุด', exact: true }).click()
  await page.waitForTimeout(800)
  await expect(page.getByText('เสร็จแล้ว · ผลจำลอง', { exact: true })).toHaveCount(1)
  await page.getByRole('button', { name: 'หยุดใช้บริบท', exact: true }).click()
  await expect(page.getByRole('complementary', { name: 'บริบทหน้าจอ' })).toContainText('ยังไม่เลือกบริบท')
  await send(page, 'วิเคราะห์งาน')
  await expect(page.getByRole('article', { name: 'คำตอบจำลอง CIC' }).last()).toContainText('แผนงานตัวอย่าง')
  await expect(page.getByRole('button', { name: 'อนุญาตการจำลองนี้' })).toHaveCount(0)
})
test('local attachments validate, preview, revoke URLs, preserve on send and never fetch attached URL', async ({ page }) => {
  const requested: string[] = []
  page.on('request', request => requested.push(request.url()))
  await page.addInitScript(() => {
    const original = URL.revokeObjectURL
    ;(window as unknown as { revoked: string[] }).revoked = []
    URL.revokeObjectURL = url => { (window as unknown as { revoked: string[] }).revoked.push(url); original(url) }
  })
  await page.goto('./#/app')
  await page.getByRole('button', { name: 'ลิงก์', exact: true }).click()
  const modal = page.getByRole('dialog', { name: 'แนบลิงก์' })
  await modal.getByRole('textbox').fill('javascript:alert(1)')
  await modal.getByRole('button', { name: 'เพิ่มลิงก์' }).click()
  await expect(modal.getByRole('alert')).toContainText('http/https')
  await modal.getByRole('textbox').fill('https://example.com/unfetched-demo')
  await modal.getByRole('button', { name: 'เพิ่มลิงก์' }).click()
  await expect(page.getByText('example.com', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'ลบ example.com' }).click()
  const upload = page.getByLabel('แนบรูปภาพ', { exact: true })
  await upload.setInputFiles({ name: 'large.png', mimeType: 'image/png', buffer: Buffer.alloc(5 * 1024 * 1024 + 1) })
  await expect(page.getByRole('alert')).toContainText('5 MB')
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aF9sAAAAASUVORK5CYII=', 'base64')
  await upload.setInputFiles({ name: 'sample.png', mimeType: 'image/png', buffer: png })
  await expect(page.getByRole('img', { name: 'ภาพแนบ sample.png' })).toBeVisible()
  await page.getByRole('button', { name: 'ลบ sample.png' }).click()
  expect(await page.evaluate(() => (window as unknown as { revoked: string[] }).revoked.length)).toBe(1)
  await upload.setInputFiles({ name: 'sample.png', mimeType: 'image/png', buffer: png })
  await send(page, 'ภาพนี้เป็นอย่างไร')
  await expect(page.getByRole('article', { name: 'คำตอบจำลอง CIC' })).toContainText('ไม่ได้อ่านหรือวิเคราะห์')
  await expect(page.getByRole('img', { name: 'ภาพแนบ sample.png' })).toBeVisible()
  expect(requested.some(url => url.includes('example.com'))).toBe(false)
  expect(await page.evaluate(() => ({ local: { ...localStorage }, session: { ...sessionStorage } }))).toEqual({ local: {}, session: {} })
})
test('modal keyboard, focus restoration and mobile navigation/context drawer', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('./#/app')
  const trigger = page.getByRole('button', { name: 'เปิดประวัติแชต' })
  await trigger.click()
  const nav = page.getByRole('dialog', { name: 'แชตของคุณ' })
  await expect(nav.getByRole('button', { name: 'ปิดแชตของคุณ' })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(nav.getByRole('link', { name: 'กลับหน้าแนะนำ', exact: true })).toBeFocused()
  await page.keyboard.press('Tab'); await expect(nav.getByRole('button', { name: 'ปิดแชตของคุณ' })).toBeFocused()
  await page.keyboard.press('Escape'); await expect(trigger).toBeFocused()
  await page.getByRole('button', { name: 'เปิดบริบท', exact: true }).click()
  await selectSource(page, 'แท็บเบราว์เซอร์')
  const context = page.getByRole('dialog', { name: 'บริบทหน้าจอ', exact: true })
  await expect(context).toContainText('แท็บตัวอย่าง — แผนงาน')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'เปิดบริบท', exact: true })).toBeFocused()
})
test('reading older messages stays put when a reply arrives; latest-message button resumes following', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 600 })
  await page.goto('./#/app')
  const chat = page.getByLabel('ข้อความในแชต', { exact: true })
  await send(page, 'งาน\n'.repeat(40))
  await expect(page.getByRole('article')).toHaveCount(2)
  await send(page, 'คำถามถัดไป')
  await chat.evaluate(el => { el.scrollTop = 0; el.dispatchEvent(new Event('scroll')) })
  await expect(page.getByRole('article')).toHaveCount(4)
  await expect(page.getByRole('button', { name: 'ข้อความใหม่ ↓' })).toBeVisible()
  expect(await chat.evaluate(el => el.scrollTop)).toBe(0)
  await page.getByRole('button', { name: 'ข้อความใหม่ ↓' }).click()
  await expect.poll(() => chat.evaluate(el => el.scrollHeight - el.scrollTop - el.clientHeight)).toBeLessThan(5)
})
test('app motion, rapid modal reopen and context toggle keep composer position', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('./#/app')
  const input = page.getByRole('textbox', { name: 'ข้อความถึง CIC' })
  const before = await input.boundingBox()
  await page.getByRole('button', { name: 'ซ่อนบริบท', exact: true }).click()
  const hidden = await input.boundingBox()
  expect(hidden).toEqual(before)
  await page.getByRole('button', { name: 'เปิดบริบท', exact: true }).click()
  await page.getByRole('button', { name: 'ลิงก์', exact: true }).click()
  const modal = page.getByRole('dialog', { name: 'แนบลิงก์' })
  expect(await modal.evaluate(el => el.getAnimations().some(a => a.effect?.getTiming().duration === 260))).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'ลิงก์', exact: true }).click()
  await expect(modal.getByRole('button', { name: 'ปิดแนบลิงก์' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(input).toBeVisible()
})
for (const viewport of [{ width: 1440, height: 900 }, { width: 1280, height: 720 }, { width: 390, height: 844 }, { width: 360, height: 480 }]) {
  test(`visual layout ${viewport.width}x${viewport.height}, long content and reduced motion`, async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', e => errors.push(e.message))
    page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`) })
    await page.setViewportSize(viewport); await page.goto('./#/app')
    await expect(page.getByRole('textbox', { name: 'ข้อความถึง CIC' })).toBeVisible()
    await page.screenshot({ path: `test-results/app-${viewport.width}-${viewport.height}.png` })
    await send(page, `ดูโค้ด\nhttps://example.com/${'long'.repeat(120)}`)
    await expect(page.locator('article pre code')).toBeVisible()
    await expect(page.getByRole('button', { name: 'ส่งข้อความ', exact: true })).toBeInViewport()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('button', { name: 'มุมมองกะทัดรัด', exact: true }).click()
    await expect(page.getByRole('article')).toHaveCount(2)
    await page.screenshot({ path: `test-results/app-compact-${viewport.width}.png` })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(await page.locator('article').first().evaluate(el => getComputedStyle(el).animationName)).toBe('none')
    if (viewport.height < 650) {
      await page.getByRole('textbox', { name: 'ข้อความถึง CIC' }).fill('ร่างข้อความยาว\n'.repeat(30))
      const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aF9sAAAAASUVORK5CYII=', 'base64')
      await page.getByLabel('แนบรูปภาพ', { exact: true }).setInputFiles({ name: 'small.png', mimeType: 'image/png', buffer: png })
      await expect(page.getByRole('img', { name: 'ภาพแนบ small.png' })).toBeVisible()
      await expect(page.getByRole('button', { name: 'ส่งข้อความ', exact: true })).toBeInViewport()
    }
    expect(errors).toEqual([])
  })
}
