import {useCallback,useEffect,useRef,useState,type PointerEvent} from 'react'
import Brand from '../Brand'
import {connectBackend,localBackendUrl,type BackendCapability} from '../workspace/transport'
import {OCR_LIMITS,imageHeader,type OcrJob,type OcrRegion,type OcrSource} from '../../shared/ocr'
import {offerReference,takeFrame} from './handoff'
import './ocr.css'
type Selected={blob:Blob;url:string;bytes:Uint8Array;width:number;height:number;source:OcrSource;capturedMono?:number;surface?:'window'|'browser'|'monitor';originalWidth?:number;originalHeight?:number}
const messages:Record<string,string>={invalid:'รูปแบบภาพหรือพื้นที่ไม่ถูกต้อง',unsupported:'รองรับ PNG 8 บิต/JPEG ที่ไม่หมุน EXIF เท่านั้น ไม่รับภาพเคลื่อนไหว',dimensions:'ขนาดภาพไม่ตรงกัน กรุณาเลือกภาพใหม่','too-large':'ภาพเกิน 4 MB / 4 ล้านพิกเซล หรือด้านเกิน 4096 พิกเซล','decode-failed':'ภาพเสียหายหรือเปิดอ่านไม่ได้','ocr-failed':'เครื่องมือ OCR อ่านไม่สำเร็จ',timeout:'OCR ใช้เวลานานเกินขอบเขต','memory-low':'RAM ว่างไม่พอ กรุณาจัดพื้นที่ว่างเองแล้วลองใหม่',busy:'มีงานในเครื่องกำลังทำอยู่ กรุณารอ',capacity:'ถึงจำนวนงานชั่วคราว กรุณาล้างผลเก่าหรือเปิดบริการใหม่','not-configured':'ยังไม่ได้ตั้งค่า OCR ใน backend เครื่องนี้','not-found':'ผลหมดอายุหรือสิทธิ์ไม่ตรง กรุณาอ่านภาพใหม่','stop-unverified':'ยังยืนยันไม่ได้ว่าตัวอ่านหยุดแล้ว ยังไม่เริ่มงานใหม่','cleanup-failed':'ล้างภาพชั่วคราวไม่สำเร็จ กรุณาตรวจบริการก่อนใช้งานต่อ',cancelled:'ยกเลิกแล้ว','output-limit':'ข้อความหรือจำนวนกรอบมากเกินขอบเขต กรุณาเลือกพื้นที่เล็กลง'}
export default function OcrPage(){
 const base=localBackendUrl(location.hostname,import.meta.env.VITE_BACKEND_URL),alive=useRef(true),epoch=useRef(0),selectedRef=useRef<Selected|null>(null),jobRef=useRef<OcrJob|null>(null),controller=useRef<AbortController|null>(null),operation=useRef<string|null>(null),transfer=useRef(false),drag=useRef<{x:number;y:number}|null>(null)
 const[zoom,setZoom]=useState(100),previewBox=useRef<HTMLDivElement|null>(null)
 const[selected,setSelected]=useState<Selected|null>(null),[regions,setRegions]=useState<OcrRegion[]>([]),[activeRegion,setActiveRegion]=useState(0),[job,setJob]=useState<OcrJob|null>(null),[edited,setEdited]=useState(''),[reviewed,setReviewed]=useState(false),[capability,setCapability]=useState<BackendCapability|null>(null),[message,setMessage]=useState('เลือกภาพหรือเฟรมเองก่อน แล้วเลือกภาษาและพื้นที่ข้อความ'),[connecting,setConnecting]=useState(false)
 const busy=job?.state==='running'||job?.state==='cancelling',request=useCallback(async(route:string,method='GET',body?:unknown,signal?:AbortSignal)=>{if(!base)throw Error('not-configured');const r=await fetch(base+route,{method,credentials:'include',redirect:'error',headers:method==='GET'?{}:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),signal});const value=await r.json();if(!r.ok)throw Error(value.code??'ocr-failed');return value},[base])
 const stop=useCallback(()=>{epoch.current++;controller.current?.abort();controller.current=null;const op=operation.current;operation.current=null;if(op&&base)void fetch(base+`/ocr/operations/${op}/cancel`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:'{}',keepalive:true}).catch(()=>{});if(alive.current&&jobRef.current?.state==='running'){setJob({...jobRef.current,state:'cancelling'});setMessage('กำลังรอตัวอ่านหยุด')}},[base])
 const clear=useCallback((update=true)=>{stop();drag.current=null;const old=jobRef.current;jobRef.current=null;if(old&&base)void fetch(base+`/ocr/jobs/${old.id}/clear`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:'{}',keepalive:true}).catch(()=>{});if(selectedRef.current)URL.revokeObjectURL(selectedRef.current.url);selectedRef.current=null;if(update&&alive.current){setSelected(null);setZoom(100);setRegions([]);setJob(null);setEdited('');setReviewed(false);setMessage('ภาพและผลในหน้านี้ถูกล้างแล้ว')}},[base,stop])
 useEffect(()=>{alive.current=true;const leave=()=>{if(location.hash!=='#/ocr'){alive.current=false;if(transfer.current){stop();if(selectedRef.current)URL.revokeObjectURL(selectedRef.current.url);selectedRef.current=null}else clear(false)}};const unload=()=>{alive.current=false;clear(false)};addEventListener('hashchange',leave);addEventListener('beforeunload',unload);return()=>{alive.current=false;if(!transfer.current)clear(false);else{stop();if(selectedRef.current)URL.revokeObjectURL(selectedRef.current.url)}removeEventListener('hashchange',leave);removeEventListener('beforeunload',unload)}},[clear,stop])
 const select=useCallback(async(blob:Blob,source?:OcrSource,extra?:Partial<Selected>)=>{
  clear();const token=epoch.current;setMessage('กำลังตรวจภาพ')
  try{if(!blob.size||blob.size>OCR_LIMITS.bytes)throw Error('too-large');const bytes=new Uint8Array(await blob.arrayBuffer()),h=imageHeader(bytes);if(!h.width||!h.height||h.width>OCR_LIMITS.side||h.height>OCR_LIMITS.side||h.width*h.height>OCR_LIMITS.pixels)throw Error('too-large');if(!alive.current||token!==epoch.current)return;const safeBlob=new Blob([bytes],{type:h.format==='PNG'?'image/png':'image/jpeg'});const bitmap=await createImageBitmap(safeBlob);const dims=[bitmap.width,bitmap.height];bitmap.close();if(dims[0]!==h.width||dims[1]!==h.height)throw Error('dimensions');if(!alive.current||token!==epoch.current)return;const image:Selected={blob:safeBlob,url:URL.createObjectURL(safeBlob),bytes,width:h.width,height:h.height,source:source??{kind:'file',sourceId:crypto.randomUUID(),frameId:crypto.randomUUID()},...extra};selectedRef.current=image;setSelected(image);setRegions([{x:0,y:0,width:h.width,height:h.height,language:'tha'}]);setActiveRegion(0);setMessage('ตรวจภาพตัวอย่าง เลือกภาษาและพื้นที่เอง เครื่องมืออาจสะกดผิดหรือตกหล่น')}
  catch(error){if(alive.current&&token===epoch.current)setMessage(messages[(error as Error).message]??'เปิดภาพไม่ได้ ไม่ส่งภาพเข้า OCR')}
 },[clear])
 useEffect(()=>{let cancelled=false;queueMicrotask(()=>{if(cancelled)return;const frame=takeFrame();if(frame&&base)void select(frame.blob,frame.source,{capturedMono:frame.capturedMono,surface:frame.surface,originalWidth:frame.originalWidth,originalHeight:frame.originalHeight})});return()=>{cancelled=true}},[base,select]) // One explicit handoff, never automatic capture.
 async function connect(){setConnecting(true);try{const state=await request('/ocr/status');if(!state.configured)throw Error('not-configured');const cap=await connectBackend(base!,AbortSignal.timeout(5000));if(alive.current){setCapability(cap);setMessage('OCR ในเครื่องพร้อม ผู้ใช้ต้องตรวจผลก่อนนำไปใช้')}}catch(error){if(alive.current)setMessage(messages[(error as Error).message]??'เชื่อมต่อไม่ได้ กรุณาตรวจ backend')}finally{if(alive.current)setConnecting(false)}}
 async function read(){
  const image=selectedRef.current;if(!image||!base||!capability)return;if(regions.some(r=>![r.x,r.y,r.width,r.height].every(Number.isInteger)||r.x<0||r.y<0||r.width<1||r.height<1||r.x+r.width>image.width||r.y+r.height>image.height)){setMessage('พื้นที่ต้องอยู่ภายในภาพ กรุณาตรวจพิกัดก่อนอ่าน');return}const previous=jobRef.current;stop();if(previous&&['ready','error','cancelled'].includes(previous.state))void request(`/ocr/jobs/${previous.id}/clear`,'POST',{}).catch(()=>{});const token=epoch.current,op=crypto.randomUUID();operation.current=op;const abort=new AbortController();controller.current=abort;setJob({id:'pending',operationId:op,state:'running',source:image.source});jobRef.current=null;setEdited('');setReviewed(false);setMessage('กำลังอ่านข้อความในเครื่อง ไม่มีการส่งภาพให้โมเดล')
  try{let binary='';for(let i=0;i<image.bytes.length;i+=32768)binary+=String.fromCharCode(...image.bytes.subarray(i,i+32768));const data=await request('/ocr/jobs','POST',{operationId:op,imageBase64:btoa(binary),width:image.width,height:image.height,regions,source:image.source},abort.signal) as OcrJob
   if(!alive.current||token!==epoch.current){void request(`/ocr/jobs/${data.id}/clear`,'POST',{}).catch(()=>{});return}jobRef.current=data;setJob(data)
   let current=data
   while(['running','cancelling'].includes(current.state)){await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{abort.signal.removeEventListener('abort',cancel);resolve()},350);const cancel=()=>{clearTimeout(timer);reject(abort.signal.reason)};abort.signal.addEventListener('abort',cancel,{once:true});if(abort.signal.aborted)cancel()});current=await request(`/ocr/jobs/${data.id}`,'GET',undefined,abort.signal);if(!alive.current||token!==epoch.current||selectedRef.current!==image)return;jobRef.current=current;setJob(current)}
   operation.current=null;controller.current=null;if(current.state==='ready'&&current.result){setEdited(current.result.text);setMessage(current.result.text?'อ่านเสร็จแล้ว เทียบภาพกับผลดิบและแก้ข้อความก่อนคัดลอกหรือนำเข้าแชต':'ไม่พบข้อความ อาจไม่มีข้อความหรือเครื่องมืออ่านไม่ได้ กรุณาตรวจภาพ')}else setMessage(messages[current.error??'cancelled']??'อ่านไม่สำเร็จ')
  }catch(error){if(alive.current&&token===epoch.current){setJob(null);setMessage(messages[(error as Error).message]??'อ่านไม่สำเร็จ กรุณาตรวจบริการแล้วลองใหม่')}}
 }
 async function cancel(){stop();const token=epoch.current,image=selectedRef.current;const id=jobRef.current?.id;if(!id){setJob(null);setMessage('ส่งคำขอยกเลิกแล้ว');return}try{let current=await request(`/ocr/jobs/${id}`) as OcrJob;while(alive.current&&token===epoch.current&&selectedRef.current===image&&['running','cancelling'].includes(current.state)){await new Promise(resolve=>setTimeout(resolve,250));current=await request(`/ocr/jobs/${id}`)}if(alive.current&&token===epoch.current&&selectedRef.current===image){setJob(current);jobRef.current=current;setMessage(messages[current.error??'cancelled']??'ยกเลิกแล้ว')}}catch{if(alive.current&&token===epoch.current)setMessage('ยืนยันสถานะไม่ได้ กรุณาตรวจบริการ ยังไม่อ้างว่าตัวอ่านหยุดแล้ว')}}
 function changeRegions(update:(rs:OcrRegion[])=>OcrRegion[]){if(busy)return;stop();const previous=jobRef.current;if(previous)void request(`/ocr/jobs/${previous.id}/clear`,'POST',{}).catch(()=>{});jobRef.current=null;setJob(null);setEdited('');setReviewed(false);setRegions(update);setMessage('พื้นที่หรือภาษาเปลี่ยนแล้ว กรุณาอ่านข้อความใหม่')}
 function point(event:PointerEvent<SVGSVGElement>){const svg=event.currentTarget,p=svg.createSVGPoint();p.x=event.clientX;p.y=event.clientY;const m=svg.getScreenCTM();if(!m||!selected)return null;const q=p.matrixTransform(m.inverse());return{x:Math.min(selected.width,Math.max(0,Math.round(q.x))),y:Math.min(selected.height,Math.max(0,Math.round(q.y)))}}
 function finishDrag(event:PointerEvent<SVGSVGElement>){if(busy){drag.current=null;return}const start=drag.current,end=point(event);drag.current=null;if(!start||!end)return;const x=Math.min(start.x,end.x),y=Math.min(start.y,end.y),width=Math.abs(start.x-end.x),height=Math.abs(start.y-end.y);if(width&&height){changeRegions(rs=>rs.map((r,i)=>i===activeRegion?{...r,x,y,width,height}:r));setReviewed(false)}}
 const result=job?.state==='ready'?job.result:undefined
 return <div className="cic-ocr"><header><Brand href="#/app"/><a href="#/app">กลับแชต</a><a href="#/screen">แชร์หน้าต่างอ่านอย่างเดียว</a></header><main><h1>อ่านข้อความจากภาพ · OCR ในเครื่อง</h1><p>เลือกภาษาและพื้นที่เอง อ่านด้วย Tesseract fast ไม่ใช้ qwen รับภาพ ผลอาจสะกดผิดหรือตกหล่น</p>{!base&&<p role="status">เว็บสาธารณะเป็น demo ไม่มีการเรียก localhost หรือส่งภาพ</p>}<div className="actions"><button disabled={!base||connecting||!!capability} onClick={()=>void connect()}>{capability?'เชื่อมต่อ OCR แล้ว':'ตรวจ OCR ในเครื่อง'}</button><label>เลือกภาพ PNG/JPEG<input type="file" accept="image/png,image/jpeg" disabled={!base} onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)void select(file)}}/></label><button onClick={()=>clear()} disabled={!selected&&!busy}>ล้างภาพและผล</button></div><p>ขอบเขต: ไม่เกิน 4 MB, 4 ล้านพิกเซล, ด้านละ 4096 พิกเซล ภาพนิ่งเท่านั้น JPEG ที่มี EXIF หมุนภาพยังไม่รองรับ</p><p role="status" aria-live="polite">{message}</p>
 {selected&&<><section aria-label="ภาพและพื้นที่ข้อความ"><h2>ภาพต้นฉบับ {selected.width}×{selected.height}</h2>{selected.capturedMono!==undefined&&<p>เฟรมจากแหล่ง {selected.source.sourceId.slice(0,8)} · อายุ ณแสดงผลครั้งนี้ {Math.max(0,Math.round((performance.now()-selected.capturedMono)/1000))} วินาที · {selected.surface==='monitor'?'ทั้งจอที่เลือก':selected.surface==='browser'?'แท็บ':'หน้าต่าง'} · ต้นฉบับสตรีม {selected.originalWidth}×{selected.originalHeight} พิกัดนี้ใช้ควบคุมเครื่องไม่ได้</p>}<p>เลือกพื้นที่ด้านล่าง แล้วลากบนภาพเพื่อกำหนดกรอบ หรือกรอกพิกัด อ่านตามลำดับพื้นที่ 1 → 2 → 3</p><label>ขยายภาพเพื่อตรวจข้อความ<select value={zoom} onChange={e=>setZoom(Number(e.target.value))}><option value={100}>100%</option><option value={200}>200%</option><option value={400}>400%</option></select></label><p>เมื่อขยายภาพ เลื่อนภาพได้ทั้งแนวนอนและแนวตั้ง</p><button disabled={!regions[activeRegion]} onClick={()=>{const box=previewBox.current,svg=box?.querySelector('svg'),r=regions[activeRegion];if(box&&svg&&r){const scale=svg.getBoundingClientRect().width/selected.width;box.scrollTo({left:Math.max(0,r.x*scale-16),top:Math.max(0,r.y*scale-box.clientHeight/4)})}}}>ดูจุดเริ่มพื้นที่ที่เลือก</button><div ref={previewBox} className="preview-box"><svg style={{width:zoom+'%',maxWidth:'none'}} className="preview" viewBox={`0 0 ${selected.width} ${selected.height}`} aria-label="ภาพตัวอย่างพร้อมกรอบข้อความ" onPointerDown={event=>{if(busy)return;drag.current=point(event);event.currentTarget.setPointerCapture(event.pointerId)}} onPointerUp={finishDrag} onPointerCancel={()=>{drag.current=null}}><image href={selected.url} width={selected.width} height={selected.height}/>{regions.map((r,i)=><rect key={i} x={r.x} y={r.y} width={r.width} height={r.height} className={i===activeRegion?'region selected':'region'}/>)}{result?.words.map((w,i)=><rect key={'word'+i} x={w.x} y={w.y} width={w.width} height={w.height} className="word"><title>{w.text}</title></rect>)}</svg></div>
 {regions.map((r,i)=><fieldset key={i} disabled={busy}><legend><button onClick={()=>setActiveRegion(i)}>พื้นที่ {i+1}{i===activeRegion?' · เลือกอยู่':''}</button></legend><label>ภาษา พื้นที่ {i+1}<select value={r.language} onChange={e=>changeRegions(rs=>rs.map((v,n)=>n===i?{...v,language:e.target.value as OcrRegion['language']}:v))}><option value="tha">ไทย</option><option value="eng">อังกฤษ</option><option value="tha+eng">ไทย + อังกฤษ</option></select></label>{(['x','y','width','height'] as const).map(key=><label key={key}>{key} พื้นที่ {i+1}<input type="number" min={key==='x'||key==='y'?0:1} max={key==='x'||key==='width'?selected.width:selected.height} value={r[key]} onChange={e=>changeRegions(rs=>rs.map((v,n)=>n===i?{...v,[key]:Number(e.target.value)}:v))}/></label>)}{regions.length>1&&<button onClick={()=>{changeRegions(rs=>rs.filter((_,n)=>n!==i));setActiveRegion(0)}}>ลบพื้นที่ {i+1}</button>}</fieldset>)}<button disabled={busy||regions.length>=3} onClick={()=>{changeRegions(rs=>[...rs,{x:0,y:0,width:selected.width,height:selected.height,language:'tha'}]);setActiveRegion(regions.length)}}>เพิ่มพื้นที่ข้อความ</button></section><div className="actions"><button disabled={!capability||busy||job?.error==='stop-unverified'||job?.error==='cleanup-failed'} onClick={()=>void read()}>อ่านข้อความ</button><button disabled={!busy} onClick={()=>void cancel()}>ยกเลิก OCR</button></div></>}
 {job&&job.id!=='pending'&&<button onClick={()=>{const token=epoch.current,image=selectedRef.current,id=job.id;void request(`/ocr/jobs/${id}`).then(value=>{if(!alive.current||token!==epoch.current||image!==selectedRef.current||jobRef.current?.id!==id)return;jobRef.current=value;setJob(value);setMessage(messages[value.error]??'ตรวจสถานะแล้ว')}).catch(()=>{if(alive.current&&token===epoch.current)setMessage('ตรวจสถานะไม่ได้')})}}>ตรวจสถานะ OCR</button>}
 {result&&<section aria-label="ผล OCR"><h2>ผล OCR — {result.engine}</h2><p>ภาษา {result.languages.join(', ')} · {Math.round(result.durationMs)} ms · กรอบ {result.words.length} รายการ ลำดับตามพื้นที่ที่คุณเลือก ไม่แสดงคะแนนความมั่นใจ</p><label>ผลดิบจาก OCR<textarea readOnly value={result.text} rows={5}/></label><label>ข้อความที่คุณแก้ไข<textarea value={edited} maxLength={OCR_LIMITS.textChars} rows={5} onChange={e=>{setEdited(e.target.value);setReviewed(false)}}/></label><details><summary>การแปลงพิกัดและลำดับอ่าน</summary>{result.transforms.map(t=><p key={t.region}>พื้นที่ {t.region+1}: จุดเริ่ม {t.cropX},{t.cropY} · ย่อ/ขยาย {t.scaleX.toFixed(3)}×{t.scaleY.toFixed(3)} กรอบแปลงกลับพิกัดภาพต้นฉบับแล้ว</p>)}<ol>{result.words.map((w,i)=><li key={i}>{w.text} · พื้นที่ {w.region+1} · {w.x.toFixed(1)},{w.y.toFixed(1)} ({w.width.toFixed(1)}×{w.height.toFixed(1)})</li>)}</ol></details><label className="review"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>ฉันเทียบภาพและตรวจข้อความแล้ว</label><div className="actions"><button disabled={!reviewed||!edited.trim()} onClick={()=>void navigator.clipboard.writeText(edited).then(()=>setMessage('คัดลอกข้อความที่ตรวจแล้ว')).catch(()=>setMessage('คัดลอกไม่ได้ เลือกข้อความและคัดลอกเองได้'))}>คัดลอกข้อความที่ตรวจ</button><button disabled={!reviewed||!edited.trim()||!capability} onClick={()=>{offerReference({jobId:job!.id,text:edited,engine:result.engine,edited:edited!==result.text,connection:capability!.kind==='live'?'live':'test',model:capability?.model});transfer.current=true;location.hash='#/app'}}>นำไปแชตใหม่ในเครื่อง</button></div><p>นำข้อความที่ตรวจแล้วไปเป็นข้อมูลอ้างอิงในแชตใหม่ คุณต้องพิมพ์คำสั่งของคุณแล้วกดส่งอีกครั้ง ไม่มีการส่งภาพหรืออ่านข้อความเป็นคำสั่งเครื่องมืออัตโนมัติ</p></section>}
 <p className="limits">ภาพอยู่ในหน่วยความจำเบราว์เซอร์และไฟล์ชั่วคราวของ backend เฉพาะระหว่างอ่าน ลบไฟล์หลังเสร็จ/ผิดพลาด/ยกเลิก ผลข้อความอยู่ในหน่วยความจำบริการไม่เกิน 10 นาทีหรือจนล้าง/ปิดบริการเพื่อใช้อ้างอิง หากเครื่องดับระหว่างงานอาจเหลือไฟล์ชั่วคราว ไม่มีการ log ภาพหรือข้อความโดยปริยาย ไม่มีการคลิก พิมพ์ หรือควบคุมเครื่อง</p></main></div>
}
