import {useCallback,useEffect,useRef,useState} from 'react'
import Brand from '../Brand'
import {localBackendUrl} from '../workspace/transport'
import {parseLabJob,parseLabObservation,type LabAction,type LabJob,type LabObservation} from '../../shared/lab'
import '../core/core.css'
import './lab.css'
const actions:Record<LabAction,string>={click:'คลิกปุ่มทดสอบหนึ่งครั้ง',type:'กรอกข้อความที่ตรวจแล้ว',slider:'ปรับตัวเลื่อนเป็น 75',scroll:'เลื่อนรายการลงหนึ่งช่วง'}
const states:Record<LabJob['state'],string>={'waiting-permission':'รอคุณตรวจแผน',queued:'รอคิวและ RAM',running:'กลับหน้าต่าง CIC Lab แล้วกดยืนยันสีเขียว',succeeded:'ทำแล้วและตรวจผลตรง',failed:'ทำไม่สำเร็จ',cancelled:'ยกเลิกแล้ว','stop-unverified':'ยังยืนยันการหยุดไม่ได้'}
const errors:Record<string,string>={memory:'RAM ยังไม่พอ ต้องว่างอย่างน้อย 608 MiB สำหรับ Lab',busy:'มีงานหรือหน้าต่างทดสอบอยู่แล้ว กรุณาหยุดก่อน',timeout:'หมดเวลา 30 วินาที กรุณาหยุดและวางแผนใหม่','geometry-changed':'หน้าต่างย้ายหรือเปลี่ยนขนาด จึงไม่ลงมือ กรุณาวางแผนใหม่','target-changed':'หน้าต่างไม่อยู่ด้านหน้า ถูกบัง หรือขนาดเปลี่ยน จึงไม่ลงมือ','uia-unsupported-or-failed':'Windows UI Automation ไม่รองรับงานนี้หรือทำไม่สำเร็จ','helper-exited':'หน้าต่าง Lab ปิดแล้ว กรุณาเปิดรอบใหม่','helper-integrity':'ไฟล์ Lab ไม่ตรงกับไฟล์ที่คอมไพล์ไว้','verification-failed':'ผลไม่ตรงเกณฑ์ จึงไม่รับรองว่าสำเร็จ',replay:'คำขอนี้ถูกใช้หรือยกเลิกแล้ว กรุณาเริ่มใหม่'}
export default function LabPage(){
 const base=localBackendUrl(location.hostname,import.meta.env.VITE_BACKEND_URL),alive=useRef(false),epoch=useRef(0),ops=useRef(new Set<string>())
 const [connected,setConnected]=useState(false),[ack,setAck]=useState(false),[observation,setObservation]=useState<LabObservation|null>(null),[job,setJob]=useState<LabJob|null>(null),[action,setAction]=useState<LabAction>('click'),[text,setText]=useState('CIC ทดสอบ 123'),[pending,setPending]=useState(false),[message,setMessage]=useState('ยังไม่ได้เปิดหน้าต่างทดสอบ')
 const request=useCallback(async(path:string,body?:unknown)=>{if(!base)throw Error('demo');const r=await fetch(base+path,{credentials:'include',redirect:'error',method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(6500)});const v=await r.json();if(r.status===401&&alive.current){epoch.current++;setPending(false);setAck(false);setConnected(false);setObservation(null);setJob(null);setMessage('บริการเริ่มใหม่หรือการเชื่อมต่อหมดอายุ ตรวจบริการและอนุญาตใหม่ ไม่มีการทำงานซ้ำ')}if(!r.ok)throw Error(v.code??'unavailable');return v},[base])
 const cancelOps=useCallback(()=>{if(base)for(const op of ops.current)void fetch(base+'/lab/operations/'+op+'/cancel',{method:'POST',credentials:'include',keepalive:true,headers:{'Content-Type':'application/json'},body:'{}'}).catch(()=>{});ops.current.clear()},[base])
 useEffect(()=>{alive.current=true;const leave=()=>{epoch.current++;const hasOwnedOperations=ops.current.size>0;cancelOps();if(base&&hasOwnedOperations)void fetch(base+'/lab/stop',{method:'POST',credentials:'include',keepalive:true,headers:{'Content-Type':'application/json'},body:'{}'}).catch(()=>{})};addEventListener('pagehide',leave);return()=>{alive.current=false;removeEventListener('pagehide',leave);leave()}},[base,cancelOps])
 useEffect(()=>{if(!job||!['queued','running','stop-unverified'].includes(job.state))return;let done=false;const token=epoch.current;const timer=setInterval(()=>{void request('/lab/jobs/'+job.taskId).then(parseLabJob).then(j=>{if(!done&&alive.current&&epoch.current===token&&j.taskId===job.taskId&&j.operationId===job.operationId){setJob(j);setMessage(errors[j.reason??'']??states[j.state])}}).catch(()=>{if(!done&&alive.current&&epoch.current===token)setMessage('ตรวจสถานะไม่ได้ ยังไม่ยืนยันการหยุด ใช้ปุ่มหยุดหรือ Ctrl+Alt+F9')})},400);return()=>{done=true;clearInterval(timer)}},[job,request])
 async function perform(fn:()=>Promise<void>){const token=epoch.current;setPending(true);try{await fn()}catch(e){if(alive.current&&token===epoch.current)setMessage(errors[(e as Error).message]??'ทำไม่ได้ กรุณาตรวจบริการหรือหยุด Lab แล้วเริ่มใหม่')}finally{if(alive.current&&token===epoch.current)setPending(false)}}
 async function connect(){const token=epoch.current;await perform(async()=>{const r=await fetch(base+'/session',{method:'POST',credentials:'include',redirect:'error',signal:AbortSignal.timeout(6500)});if(!r.ok)throw Error('session');if(alive.current&&token===epoch.current){setConnected(true);setMessage('เชื่อมบริการแล้ว ต้องยืนยันขอบเขตก่อนเปิด Lab')}})}
 async function open(){const token=epoch.current,op=crypto.randomUUID();ops.current.add(op);await perform(async()=>{let o:LabObservation;try{o=parseLabObservation(await request('/lab/open',{version:1,operationId:op,acknowledged:ack}))}catch(e){void request('/lab/operations/'+op+'/cancel',{}).catch(()=>{});throw e}if(alive.current&&token===epoch.current){setObservation(o);setMessage('เปิด CIC Lab แล้ว ไม่มี input อัตโนมัติ วางแผนงานหนึ่งครั้ง')}})}
 async function plan(){const token=epoch.current,op=crypto.randomUUID();ops.current.add(op);await perform(async()=>{const j=parseLabJob(await request('/lab/plans',{version:1,operationId:op,action,text:action==='type'?text:''}));if(j.operationId!==op)throw Error('protocol');if(alive.current&&token===epoch.current){setJob(j);setMessage('ตรวจแผนก่อนอนุญาต แล้วกลับไปยืนยันในหน้าต่าง Lab')}})}
 async function approve(){if(!job)return;const token=epoch.current,id=job.taskId;await perform(async()=>{const j=parseLabJob(await request('/lab/jobs/'+id+'/approve',{}));if(j.taskId!==id||j.operationId!==job.operationId)throw Error('protocol');if(alive.current&&token===epoch.current){setJob(j);setMessage(states[j.state])}})}
 async function stop(){epoch.current++;cancelOps();setPending(false);setAck(false);setJob(null);setObservation(null);const token=epoch.current;try{const r=await request('/lab/stop',{});if(alive.current&&token===epoch.current)setMessage(r.settled===true?'บริการตรวจว่าโปรเซส Lab ของคุณออกแล้ว':'ยังยืนยันการหยุดไม่ได้')}catch{if(alive.current&&token===epoch.current)setMessage('ส่งหยุดไม่ได้ ใช้ปุ่มหยุดใน CIC Lab หรือ Ctrl+Alt+F9 การหลุดไม่ใช่หลักฐานว่าหยุด')}}
 const active=!!job&&['waiting-permission','queued','running','stop-unverified'].includes(job.state)
 return <div className="cic-core cic-lab"><header><Brand href="#/app"/><a href="#/core">Core</a><a href="#/screen">แชร์ภาพอ่านอย่างเดียว</a><a href="#/app">แชต</a></header><main><h1>ทดลองควบคุม · CIC Lab เท่านั้น</h1><p>เปิดหน้าต่างทดสอบ Windows ของ CIC และให้เครื่องมือ UI Automation คลิก กรอกข้อความ ปรับตัวเลื่อน หรือเลื่อนรายการ จากนั้นตรวจผลจริง ข้อความและตำแหน่งมาจากตัวควบคุมที่มีโครงสร้าง ไม่ใช่ qwen มองภาพ</p><p>ไม่มีการควบคุมแอปอื่น เมาส์ลากจริง คีย์บอร์ดลัด ไมค์ หรือการส่งข้อมูลออก แชร์จอเดิมเป็นอ่านอย่างเดียวและไม่ได้ให้สิทธิ์หน้านี้</p>{!base&&<p>เว็บสาธารณะเป็น demo ไม่เปิดหน้าต่างหรือเรียก localhost</p>}<div className="actions"><button disabled={!base||pending||connected} onClick={()=>void connect()}>ตรวจบริการ Lab</button><button disabled={!base||!connected} onClick={()=>void stop()}>หยุดและปิด Lab ของฉัน</button></div><p role="status">{message}</p>
 <section><h2>1 · เปิดขอบเขตทดสอบ</h2><label><input type="checkbox" checked={ack} disabled={!base||!!observation||pending} onChange={e=>setAck(e.target.checked)}/>อนุญาตเฉพาะหน้าต่าง CIC Lab ที่สร้างรอบนี้ ตรวจงานทีละครั้ง ไม่ใช่สิทธิ์ทั้งเครื่อง</label><button disabled={!base||!connected||!ack||!!observation||pending} onClick={()=>void open()}>เปิดหน้าต่าง CIC Lab</button><p>หยุดได้จากเว็บ ปุ่มแดงใน Lab, Esc ใน Lab หรือ Ctrl+Alt+F9 ปิดหน้าต่างแล้วสิทธิ์ไม่กลับมาเอง ออกจากหน้านี้จะขอหยุด ถ้า backend ขาด heartbeat เกิน 2 วินาที Lab จะปิดเอง</p>{observation&&<><p>แหล่ง: หน้าต่างของโปรเซส CIC Lab · DPI: {observation.dpi} · จุดกำเนิดและตำแหน่งเป็นพิกัด Windows จริงของ Lab</p><ul>{observation.targets.map(t=><li key={t.id}>{t.name}: ({t.x}, {t.y}) · {t.width}×{t.height}</li>)}</ul><p>ตำแหน่งนี้ใช้ตรวจ geometry ใน Lab เท่านั้น ไม่แปลงภาพ OCR หรือ browser capture ไปคลิกแอปอื่น</p></>}</section>
 <section><h2>2 · เลือกงานและตรวจแผน</h2><label>งานทดสอบ<select value={action} disabled={pending||active} onChange={e=>setAction(e.target.value as LabAction)}>{Object.entries(actions).map(([id,title])=><option key={id} value={id} disabled={!!observation&&!observation.availableActions.includes(id as LabAction)}>{title}</option>)}</select></label>{action==='type'&&<label>ข้อความที่จะกรอก<input value={text} maxLength={40} disabled={pending||active} onChange={e=>setText(e.target.value)}/></label>}<button disabled={!base||!observation||pending||active||action==='type'&&!text.trim()} onClick={()=>void plan()}>วางแผน Lab หนึ่งงาน</button>{job&&<article aria-label="งาน Lab"><h3>{states[job.state]}</h3><p>{actions[job.action]} {job.action==='type'&&'→ '+job.text}</p><p>แผนหมดอายุใน 30 วินาที ทำหนึ่งครั้งเท่านั้น หากย้าย/ย่อ/เปลี่ยนขนาดหรือบังหน้าต่างจะหยุด ต้องวางแผนใหม่</p>{job.state==='waiting-permission'&&<button disabled={pending} onClick={()=>void approve()}>อนุญาตแผนนี้หนึ่งครั้ง</button>}{job.reason&&<p>{errors[job.reason]??job.reason}</p>}{job.result&&<><p>ผลเครื่องมือ native UIA · ตรวจสถานะหลังทำ · ไม่ใช่คำตอบโมเดล</p><pre>{job.result.text}</pre></>}<ol>{job.events.map((e,i)=><li key={i}>{states[e.state]} · {Math.round(e.elapsedMs)} ms</li>)}</ol><button disabled={pending||active} onClick={()=>{setJob(null);setMessage('เลือกงานใหม่แล้ววางแผนอีกครั้ง')}}>เตรียมงานถัดไป</button></article>}</section>
 <section><h2>ขอบเขตการพิสูจน์</h2><p>ต้นแบบสำหรับผู้ใช้ทดสอบ native UIA ในหน้าต่างที่เป็นเจ้าของเอง ปุ่มสีเขียวเป็นการยืนยันโดยผู้ใช้ ไม่ใช่ CIC คลิกให้ ผล fixtures และผลผู้ใช้ต้องแยกกัน ไม่รับรองทุกแอป ทุก DPI หลายจอ หรือการหยุดภายใน 500 ms จนตรวจจริงครบ</p><p>ข้อความงานและสถานะอยู่ใน RAM ไม่ log โดยปริยาย ไม่มี clipboard หรือภาพหน้าจอเก็บจาก Lab งานหมดอายุใน 10 นาที เปิดรอบใหม่ต้องอนุญาตใหม่</p></section></main></div>
}
