import {useCallback,useEffect,useRef,useState} from 'react'
import Brand from '../Brand'
import {localBackendUrl} from '../workspace/transport'
import {parseCoreCapabilities,parseCoreJob,type CoreCapabilities,type CoreJob,type CoreState} from '../../shared/core'
import './core.css'
const states:Record<CoreState,string>={idle:'พร้อมรับงาน',planned:'วางแผนแล้ว','waiting-permission':'รอคุณตรวจและอนุญาต',queued:'อยู่ในคิว',running:'กำลังทำ',verifying:'กำลังตรวจผล',succeeded:'สำเร็จและตรวจผลแล้ว',failed:'ทำไม่สำเร็จ',cancelling:'กำลังหยุด',cancelled:'ยกเลิกแล้ว','stop-unverified':'ยังยืนยันว่าตัวทำงานหยุดไม่ได้'}
const titles:Record<string,string>={readOnlyCapture:'แชร์ภาพแบบอ่านอย่างเดียว',reviewedOCR:'OCR ที่ให้ผู้ใช้ตรวจ',structuredObservation:'รู้จักหน้าต่างและปุ่มจริง',desktopControl:'คลิกและพิมพ์บนเครื่อง',voiceInput:'ฟังคำสั่งภาษาไทย',thaiSpeechOutput:'พูดตอบภาษาไทย',webResearch:'ค้นเว็บพร้อมหลักฐาน',workspaceEdit:'แก้ไฟล์ในพื้นที่ที่เลือก',animatedSlides:'สไลด์เคลื่อนไหว'}
const reasonText:Record<string,string>={memory:'RAM ไม่พอ: ต้องมีพื้นที่ว่างอย่างน้อย 520 MiB ก่อนเริ่ม','legacy-busy':'รอแชต/หมากรุก/สไลด์/OCR เดิม',timeout:'งานหมดเวลารอ กรุณาจัด RAM หรือลองเมื่อเครื่องมืออื่นว่างแล้ว','tool-failed':'เครื่องมือคำนวณไม่ได้ กรุณาตรวจรูปแบบและตัวเลข','verification-failed':'ผลไม่ตรงเงื่อนไข จึงไม่รับรองว่าสำเร็จ','permission-denied':'สิทธิ์งานหมดอายุ ถูกตัด หรือไม่ตรงกับงาน','executor-not-settled':'ตัวทำงานยังไม่ยืนยันว่าหยุด ช่องงานจึงยังถูกล็อก',cancelled:'ยกเลิกตามคำขอแล้ว',busy:'คิวเต็มหรือคุณมีงานกำลังรออยู่',unsupported:'รองรับเฉพาะ /calc และ /time ในรอบนี้',invalid:'รูปแบบคำสั่งไม่ถูกต้อง',capacity:'จำนวนงานถึงขอบเขตที่กำหนด กรุณารอให้หมดอายุ',replay:'คำขอนี้ถูกยกเลิกหรือใช้แล้ว กรุณาวางแผนใหม่'}
const terminal=(state:CoreState)=>['succeeded','failed','cancelled'].includes(state)
export default function CorePage(){
 const base=localBackendUrl(location.hostname,import.meta.env.VITE_BACKEND_URL),alive=useRef(true),epoch=useRef(0),operation=useRef<string|null>(null),controller=useRef<AbortController|null>(null)
 const [cap,setCap]=useState<CoreCapabilities|null>(null),[job,setJob]=useState<CoreJob|null>(null),[instruction,setInstruction]=useState('/calc (24 + 18) / 6'),[message,setMessage]=useState('ยังไม่ได้เชื่อมบริการในเครื่อง'),[pending,setPending]=useState(false)
 const request=useCallback(async(path:string,body?:unknown,signal?:AbortSignal)=>{if(!base)throw Error('เว็บนี้เป็น demo');const r=await fetch(base+path,{method:body===undefined?'GET':'POST',credentials:'include',redirect:'error',headers:body===undefined?{}:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.any([signal??new AbortController().signal,AbortSignal.timeout(6000)])});if(r.status===401){if(alive.current){epoch.current++;controller.current?.abort();operation.current=null;setCap(null);setJob(null);setPending(false);setMessage('การเชื่อมต่อหมดอายุหรือบริการเริ่มใหม่ กดตรวจบริการอีกครั้ง งานเก่าไม่ถูกเริ่มซ้ำ และการหลุดไม่ใช่หลักฐานว่าตัวทำงานหยุดแล้ว')}throw Error('unauthorized')}const data=await r.json();if(!r.ok)throw Error(typeof data.code==='string'?data.code:'unavailable');return data},[base])
 const invalidate=useCallback(()=>{epoch.current++;controller.current?.abort();controller.current=null;const op=operation.current;operation.current=null;if(op&&base)void request('/core/operations/'+op+'/cancel',{}).catch(()=>{});},[base,request])
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;invalidate()}},[invalidate])
 useEffect(()=>{
  if(!job||terminal(job.state))return
  let stopped=false;const id=job.taskId,token=epoch.current,abort=new AbortController();let timer:ReturnType<typeof setTimeout>
  const poll=async()=>{try{const next=parseCoreJob(await request('/core/jobs/'+id,undefined,abort.signal));if(stopped||!alive.current||token!==epoch.current)return;if(next.taskId!==id||next.operationId!==job.operationId)throw Error('protocol');setJob(next);setMessage(reasonText[next.reason??'']??states[next.state]);if(!terminal(next.state))timer=setTimeout(()=>void poll(),500)}catch{if(!stopped&&alive.current&&token===epoch.current)setMessage('ตรวจสถานะไม่ได้ ยังไม่ยืนยันว่าหยุด ใช้ปุ่มหยุดทั้งหมดหรือตรวจบริการ') }}
  timer=setTimeout(()=>void poll(),300);return()=>{stopped=true;clearTimeout(timer);abort.abort()}
 },[job,request])
 async function connect(){const token=epoch.current;setPending(true);try{const response=await fetch(base+'/session',{method:'POST',credentials:'include',redirect:'error',signal:AbortSignal.timeout(6000)});if(!response.ok)throw Error('session');const profile=parseCoreCapabilities(await request('/core/capabilities'));if(alive.current&&token===epoch.current){setCap(profile);setMessage('พร้อมวางแผนงานเลข/เวลา ไม่เรียกโมเดลและไม่ควบคุมเครื่อง')}}catch{if(alive.current&&token===epoch.current)setMessage('เชื่อมบริการไม่ได้ กรุณาตรวจ backend ในเครื่อง')}finally{if(alive.current&&token===epoch.current)setPending(false)}}
 async function plan(){invalidate();setJob(null);const token=epoch.current,op=crypto.randomUUID(),abort=new AbortController();operation.current=op;controller.current=abort;setPending(true)
  try{const next=parseCoreJob(await request('/core/plans',{version:1,operationId:op,instruction},abort.signal));if(next.operationId!==op)throw Error('protocol');if(alive.current&&token===epoch.current){setJob(next);setMessage('ตรวจคำสั่งและขอบเขตของแผนก่อนอนุญาต งานนี้คำนวณในเครื่องเท่านั้น')}}catch(e){if(alive.current&&token===epoch.current)setMessage(reasonText[(e as Error).message]??'วางแผนไม่ได้ กรุณาตรวจคำสั่งและบริการ')}finally{if(alive.current&&token===epoch.current)setPending(false)}
 }
 async function approve(){if(!job)return;const id=job.taskId,token=epoch.current;setPending(true);try{const next=parseCoreJob(await request('/core/jobs/'+id+'/approve',{}));if(next.taskId!==id||next.operationId!==job.operationId)throw Error('protocol');if(alive.current&&token===epoch.current){setJob(next);setMessage(reasonText[next.reason??'']??states[next.state])}}catch{if(alive.current&&token===epoch.current)setMessage('เริ่มไม่ได้ แผนอาจหมดอายุหรือสิทธิ์ถูกตัด กรุณาวางแผนใหม่')}finally{if(alive.current&&token===epoch.current)setPending(false)}}
 async function stop(){invalidate();const token=epoch.current;setPending(false);try{const result=await request('/core/stop',{});if(!alive.current||token!==epoch.current)return;setMessage(result.settled===true?'บริการยืนยันว่าไม่มีงาน Core ของคุณกำลังทำ':'รับคำขอหยุดแล้ว แต่ยังไม่ยืนยันว่าตัวทำงานหยุด');if(job)setJob(parseCoreJob(await request('/core/jobs/'+job.taskId)))}catch{if(alive.current&&token===epoch.current)setMessage('ส่งคำขอหยุดไม่ได้ ยังไม่ยืนยันการหยุด กรุณาตรวจ backend')}}
 const active=!!job&&!terminal(job.state)
 return <div className="cic-core"><header><Brand href="#/app"/><a href="#/app">กลับแชต</a><a href="#/ocr">OCR</a><a href="#/screen">แชร์ภาพ</a></header><main><h1>Core · งานและความสามารถจริง</h1><p>เริ่มด้วยเลขและเวลา: วางแผน → คุณอนุญาต → ทำงาน → ตรวจผล ไม่มีการคลิก พิมพ์ ใช้ไมค์ หรือส่งข้อมูลออก</p>{!base&&<p role="status">เว็บสาธารณะเป็น demo ไม่เรียกบริการในเครื่อง</p>}<div className="actions"><button disabled={!base||pending||!!cap} onClick={()=>void connect()}>ตรวจบริการและความสามารถ</button><button disabled={!base||!cap} onClick={()=>void stop()}>หยุดงาน Core ทั้งหมดของฉัน</button></div><p role="status">{message}</p>
 <section><h2>งานที่รองรับ</h2><p>ใช้ /calc ตามด้วยเลขและเครื่องหมาย หรือ /time HH:MM + นาที แผนใช้ได้ 30 วินาที คิวรอสองงานและทำทีละงาน เมื่อ RAM ไม่พอจะรอหรือหมดเวลา ไม่ลด guard</p><label>คำสั่งของคุณ<textarea maxLength={160} value={instruction} disabled={pending||(active&&job?.state!=='waiting-permission')} onChange={e=>{invalidate();setJob(null);setInstruction(e.target.value)}}/></label><button disabled={!base||!cap||pending||active||!instruction.trim()} onClick={()=>void plan()}>วางแผนงาน</button>{job&&<article aria-label="งาน Core"><h3>{states[job.state]}</h3><p>เครื่องมือ: {job.toolId==='calculator'?'คำนวณเลข':'คำนวณเวลา'} · สิทธิ์คำนวณในเครื่องหนึ่งครั้ง</p><p className="expression">{job.args.expression}</p>{job.state==='waiting-permission'&&<button disabled={pending} onClick={()=>void approve()}>อนุญาตงานนี้และเริ่ม</button>}{job.reason&&<p>{reasonText[job.reason]??'บริการรายงานข้อจำกัดของงาน กรุณาตรวจแล้วลองใหม่'}</p>}{job.result&&<><p>ผลเครื่องมือในเครื่อง · ตรวจผลแล้ว · ไม่ใช่คำตอบโมเดล</p><pre>{job.result.text}</pre></>}<ol aria-label="ลำดับสถานะงาน">{job.events.map(e=><li key={e.sequence}>{states[e.state]} · {Math.round(e.elapsedMs)} ms</li>)}</ol></article>}</section>
 <section><h2>ความพร้อมแต่ละความสามารถ</h2><p>มีโค้ด ไม่เท่ากับตั้งค่าพร้อม มีสิทธิ์ หรือผ่านการยอมรับครบ ค่า “สิทธิ์ยังไม่ให้” เป็นค่าเริ่มต้นของงาน Core ไม่ใช่การอ่านสิทธิ์ browser picker</p>{cap?cap.capabilities.map(c=><article key={c.id}><h3>{titles[c.id]}</h3><p>{c.detail}</p><p>มีโค้ด: {c.implemented?'มี':'ยังไม่มี'} · ตั้งค่า: {c.configured===null?'ต้องตรวจในเบราว์เซอร์':c.configured?'พร้อม':'ยังไม่พร้อม'} · สุขภาพ: {c.healthy===null?'ยังไม่ทราบ':c.healthy?'ตั้งค่าตรงเงื่อนไข':'ยังไม่พร้อม'}</p><p>สิทธิ์ Core: {c.authorized?'มี':'ยังไม่ให้'} · ยอมรับครบ: {c.accepted?'ผ่าน':'ยังไม่ผ่านครบ'} · {c.mode==='manual'?'ผู้ใช้เลือกและตรวจเอง':'ปิดใช้งาน'}</p></article>):<p>ยังไม่ได้ตรวจสถานะจากบริการ ไม่แสดงว่า agent พร้อมโดยไม่มีหลักฐาน</p>}</section></main></div>
}
