import {randomUUID} from 'node:crypto'
import {freemem} from 'node:os'
import {CoreError,exact,uuid} from '../../shared/core.js'
import {parseLabPlan,type LabJob} from '../../shared/lab.js'
import {createScheduler} from '../core/scheduler.js'
import {startNativeLab,type LabNative} from './native.js'
type Stored={owner:string;job:LabJob;deadline:number;created:number;abort:AbortController;geometry:string;instance:string;used:boolean;timer:ReturnType<typeof setTimeout>}
export function createLabCore(opts:{scheduler?:ReturnType<typeof createScheduler>;externalBusy:()=>boolean;ownerAlive:(owner:string)=>boolean;freeMiB?:()=>number;start?:()=>Promise<LabNative>;deadlineMs?:number} ){
 let native:LabNative|null=null,owner:string|null=null,opening=false,closing=false,startPromise:Promise<LabNative>|null=null,openingOperation:string|null=null,stopping:Promise<{settled:boolean}>|null=null;const jobs=new Map<string,Stored>(),operations=new Map<string,ReturnType<typeof setTimeout>>(),cancelledOperations=new Set<string>(),clock=()=>performance.now()
 const scheduler=opts.scheduler??createScheduler({freeMiB:opts.freeMiB??(()=>freemem()/1048576),externalBusy:opts.externalBusy})
 const state=(s:Stored,next:LabJob['state'],reason?:string)=>{s.job.state=next;s.job.reason=reason;if(s.job.events.length<12)s.job.events.push({state:next,elapsedMs:clock()-s.created})}
 const view=(s:Stored)=>structuredClone(s.job),owned=(who:string,id:string)=>{const s=jobs.get(id);if(!s||s.owner!==who)throw new CoreError('not-found');return s}
 function remember(who:string,op:string){if(!uuid(op))throw new CoreError('invalid');const key=who+':'+op;if(operations.has(key))throw new CoreError('replay');if(operations.size>=128)throw new CoreError('capacity');const t=setTimeout(()=>{operations.delete(key);cancelledOperations.delete(key)},600000);t.unref();operations.set(key,t)}
 async function stop(who:string){
  if(owner&&owner!==who)throw new CoreError('not-found');if(stopping)return stopping;closing=true
  for(const s of jobs.values())if(s.owner===who){clearTimeout(s.timer);if(!['succeeded','failed','cancelled'].includes(s.job.state)){s.abort.abort();scheduler.remove(s.job.taskId);state(s,'stop-unverified','checking-exit')}}
  stopping=(async()=>{const worker=native??await startPromise?.catch(()=>null);if(worker)await worker.close();for(const s of jobs.values())if(s.owner===who&&s.abort.signal.aborted)state(s,'cancelled','owned-helper-exit-verified');return{settled:true}})()
  try{return await stopping}finally{native=null;owner=null;openingOperation=null;closing=false;stopping=null}
 }
 async function execute(s:Stored){state(s,'running','confirm-in-native-window');try{
  if(s.used||s.abort.signal.aborted||clock()>=s.deadline||!opts.ownerAlive(s.owner)||owner!==s.owner||!native?.alive())throw new CoreError('permission-denied')
  const worker=native;const fresh=await worker.observe();s.abort.signal.throwIfAborted();if(worker!==native||fresh.instanceId!==s.instance||fresh.geometry!==s.geometry)throw new CoreError('geometry-changed');s.used=true
  const result=await worker.execute(s.job.action,s.job.text,s.geometry,s.abort.signal,{taskId:s.job.taskId,operationId:s.job.operationId,grantId:randomUUID(),observationId:fresh.observationId,deadlineMs:fresh.monotonicMs+Math.max(0,s.deadline-clock())});s.abort.signal.throwIfAborted()
  if(clock()>=s.deadline||!opts.ownerAlive(s.owner)||result.before.instanceId!==s.instance||result.after.instanceId!==s.instance||result.before.geometry!==s.geometry||result.after.geometry!==s.geometry||!result.before.foreground||!result.after.foreground)throw new CoreError('verification-failed')
  const a=result.after,b=result.before,action=s.job.action;const pass=action==='click'?a.clicks===b.clicks+1:action==='type'?a.text===s.job.text:action==='slider'?a.slider===75:a.top>b.top
  if(!pass)throw new CoreError('verification-failed');s.job.result={source:'native-uia-lab',verified:true,text:action==='click'?'ปุ่มได้รับคลิก: '+a.clicks:action==='type'?'ช่องข้อความ: '+a.text:action==='slider'?'ตัวเลื่อน: '+a.slider:'รายการเลื่อนไปที่: '+a.top};state(s,'succeeded')
 }catch(e){delete s.job.result;if(s.job.state==='stop-unverified')return;state(s,s.abort.signal.aborted?'cancelled':'failed',e instanceof CoreError?e.code:'native-failed')}finally{clearTimeout(s.timer)}}
 const sessionWatch=setInterval(()=>{if(owner&&!opts.ownerAlive(owner))void stop(owner).catch(()=>{})},250);sessionWatch.unref()
 return{
  async open(who:string,value:unknown){if(!exact(value,['version','operationId','acknowledged'])||value.version!==1||!uuid(value.operationId)||value.acknowledged!==true)throw new CoreError('permission-denied');remember(who,value.operationId);if(opening||closing||native?.alive())throw new CoreError('busy');if(opts.externalBusy()||(opts.freeMiB??(()=>freemem()/1048576))()<608)throw new CoreError('memory');opening=true;owner=who;openingOperation=value.operationId;try{if(native){await native.close();native=null}startPromise=(opts.start??startNativeLab)();const worker=await startPromise;if(owner!==who||closing||cancelledOperations.has(who+':'+value.operationId)){await worker.close();throw new CoreError('cancelled')}native=worker;return await native.observe()}finally{opening=false;startPromise=null;if(!native&&owner===who)owner=null}},
  async observe(who:string){if(owner!==who||!native?.alive())throw new CoreError('not-found');return await native.observe()},
  async plan(who:string,value:unknown){const p=parseLabPlan(value);if(owner!==who||!native?.alive()||closing)throw new CoreError('not-found');if(jobs.size>=32||[...jobs.values()].filter(s=>s.owner===who).length>=8)throw new CoreError('capacity');remember(who,p.operationId);const o=await native.observe();if(!o.availableActions.includes(p.action))throw new CoreError('uia-unsupported-or-failed');if(cancelledOperations.has(who+':'+p.operationId))throw new CoreError('cancelled');if(!native?.alive()||owner!==who)throw new CoreError('cancelled');const created=clock(),deadline=created+(opts.deadlineMs??30000),taskId=randomUUID();const s:Stored={owner:who,geometry:o.geometry,instance:o.instanceId,created,deadline,used:false,abort:new AbortController(),job:{version:1,taskId,operationId:p.operationId,action:p.action,text:p.text,state:'waiting-permission',events:[]},timer:setTimeout(()=>{s.abort.abort();scheduler.remove(taskId);if(s.job.state==='running'){state(s,'stop-unverified','timeout');void stop(who)}else if(s.job.state!=='succeeded'&&s.job.state!=='failed')state(s,'failed','timeout')},opts.deadlineMs??30000)};s.timer.unref();jobs.set(taskId,s);state(s,'waiting-permission');const expiry=setTimeout(()=>{if(!['succeeded','failed','cancelled'].includes(s.job.state))void stop(who);else jobs.delete(taskId)},600000);expiry.unref();return view(s)},
  approve(who:string,id:string){const s=owned(who,id);if(s.job.state!=='waiting-permission'||clock()>=s.deadline||s.abort.signal.aborted||owner!==who||!native?.alive())throw new CoreError('permission-denied');state(s,'queued');try{scheduler.enqueue({id,owner:who,reserveMiB:96,deadline:s.deadline,cancelled:()=>s.abort.signal.aborted,onWait:r=>{s.job.reason=r},run:()=>execute(s),onError:r=>{s.abort.abort();state(s,'failed',r)}})}catch(e){state(s,'failed','busy');throw e}return view(s)},
  get:(who:string,id:string)=>view(owned(who,id)),
  async cancelOperation(who:string,op:string){if(!uuid(op))throw new CoreError('invalid');if(!operations.has(who+':'+op))remember(who,op);cancelledOperations.add(who+':'+op);if(owner===who&&openingOperation===op){await stop(who);return}const s=[...jobs.values()].find(s=>s.owner===who&&s.job.operationId===op);if(s){clearTimeout(s.timer);s.abort.abort();scheduler.remove(s.job.taskId);if(s.job.state==='running')await stop(who);else if(!['succeeded','failed'].includes(s.job.state))state(s,'cancelled')}},
  stop,isBusy:()=>opening||closing||scheduler.busy(),
  async close(){clearInterval(sessionWatch);if(owner)await stop(owner);scheduler.close();for(const s of jobs.values())clearTimeout(s.timer);for(const t of operations.values())clearTimeout(t);operations.clear();cancelledOperations.clear();jobs.clear()},
 }
}
